<a href="https://colab.research.google.com/github/Otto-C/Otto-C.github.io/blob/main/01_Bullion_API_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata

api_key = userdata.get('METALS_API_KEY')

print("API key loaded successfully!" if api_key else "API key not found")

API key loaded successfully!

In [2]:
import requests
url = 'https://api.metals.dev/v1/latest'

params = {
    "api_key": api_key,
    "currency": "ZAR",
    "unit": "toz"
}

response = requests.get(url, params=params, timeout=30)

print("HTTP Status", response.status_code)
print("API Status", response.json().get("status"))

HTTP Status 200
API Status success

In [3]:
data = response.json()
print(data)

{'status': 'success', 'currency': 'ZAR', 'unit': 'toz', 'metals': {'gold': 68516.2421, 'silver': 975.1443, 'platinum': 27393.0297, 'palladium': 18571.8569, 'lbma_gold_am': 69026.375, 'lbma_gold_pm': 68812.6506, 'lbma_silver': 993.6946, 'lbma_platinum_am': 27761.0648, 'lbma_platinum_pm': 27874.1159, 'lbma_palladium_am': 18993.4138, 'lbma_palladium_pm': 18992.5886, 'mcx_gold': 80097.3196, 'mcx_gold_am': 79297.157, 'mcx_gold_pm': 79388.3438, 'mcx_silver': 1182.8019, 'mcx_silver_am': 1182.6237, 'mcx_silver_pm': 1183.5248, 'ibja_gold': 79649.6223, 'ibja_silver': 1181.8315, 'copper': 7.6576, 'aluminum': 1.5501, 'lead': 0.9715, 'nickel': 7.9619, 'zinc': 1.8951, 'lme_copper': 7.5241, 'lme_aluminum': 1.5708, 'lme_lead': 0.9676, 'lme_nickel': 8.0695, 'lme_zinc': 1.9301}, 'currencies': {'AED': 4.49389069, 'AFN': 0.25418233, 'ALL': 0.20212972, 'AMD': 0.0455835, 'ANG': 9.16919216, 'AOA': 0.01803796, 'ARS': 0.01090409, 'AUD': 11.51999092, 'AWG': 9.22000757, 'AZN': 9.70812566, 'BAM': 9.44610438, 'BBD': 8.25190678, 'BDT': 0.13402174, 'BGN': 9.44610438, 'BHD': 43.89312115, 'BIF': 0.00550557, 'BMD': 16.50381355, 'BND': 12.89409228, 'BOB': 1.40816775, 'BRL': 3.29067525, 'BSD': 16.50381355, 'BTC': 1370782.78973121, 'BTN': 0.17347178, 'BWP': 1.21220098, 'BYN': 5.50127118, 'BYR': 0.0006034, 'BZD': 8.2081929, 'CAD': 11.60875218, 'CDF': 0.00714824, 'CHF': 19.81173906, 'CLP': 0.0168128, 'CNH': 2.46568983, 'CNY': 2.46578026, 'COP': 0.00517645, 'CRC': 0.0362445, 'CUC': 16.50381355, 'CUP': 0.6876589, 'CVE': 0.16754307, 'CZK': 0.75870146, 'DJF': 0.09265383, 'DKK': 2.47145376, 'DOP': 0.26946396, 'DZD': 0.12266243, 'EEK': 1.18076305, 'EGP': 0.31263888, 'ERN': 1.10025424, 'ETB': 0.10240573, 'EUR': 18.47497434, 'FJD': 7.31848257, 'FKP': 21.86508804, 'GBP': 21.86508804, 'GEL': 6.36575646, 'GGP': 21.86508804, 'GHS': 1.41131714, 'GIP': 21.86508804, 'GMD': 0.22196621, 'GNF': 0.00187378, 'GTQ': 2.1597572, 'GYD': 0.07889589, 'HKD': 2.10283204, 'HNL': 0.61403023, 'HRK': 2.45205048, 'HTG': 0.1256659, 'HUF': 0.05077736, 'IDR': 0.00092188, 'ILS': 5.37046298, 'IMP': 21.86508804, 'INR': 0.17347178, 'IQD': 0.01089374, 'IRR': 9.17e-06, 'ISK': 0.13559425, 'JEP': 21.86508804, 'JMD': 0.10408174, 'JOD': 23.27759316, 'JPY': 0.10421579, 'KES': 0.12722742, 'KGS': 0.18871016, 'KHR': 0.00405528, 'KMF': 0.03755322, 'KPW': 0.01833476, 'KRW': 0.01230123, 'KWD': 53.02146346, 'KYD': 19.87910744, 'KZT': 0.03669269, 'LAK': 0.0007366, 'LBP': 0.00018339, 'LKR': 0.04987718, 'LRD': 0.09646126, 'LSL': 1, 'LTL': 5.35072241, 'LVL': 26.28766981, 'LYD': 2.56663969, 'MAD': 1.68276146, 'MDL': 0.91905425, 'MGA': 0.00365312, 'MKD': 0.29992627, 'MMK': 0.00786, 'MNT': 0.00458913, 'MOP': 2.04158451, 'MRU': 0.41110552, 'MUR': 0.34621557, 'MVR': 1.06752014, 'MWK': 0.00953533, 'MXN': 0.89777326, 'MYR': 4.03287211, 'MZN': 0.25892266, 'NAD': 1, 'NGN': 0.01242537, 'NIO': 0.44837671, 'NOK': 1.7326185, 'NPR': 0.10836907, 'NTD': 0.5565185, 'NZD': 9.26378366, 'OMR': 42.89151498, 'PAB': 16.50381355, 'PEN': 4.80597264, 'PGK': 3.7145883, 'PHP': 0.26292666, 'PKR': 0.05958469, 'PLN': 4.22620859, 'PYG': 0.00288821, 'QAR': 4.53401471, 'RON': 3.46014011, 'RSD': 0.1573632, 'RUB': 0.19731963, 'RWF': 0.01118887, 'SAR': 4.40101695, 'SBD': 2.04603568, 'SCR': 1.12392962, 'SDG': 0.02749894, 'SEK': 1.65495631, 'SGD': 12.89409228, 'SHP': 21.86508804, 'SKK': 0.6132568, 'SLE': 0.71912055, 'SLL': 0.000727, 'SOS': 0.02890192, 'SPL': 99.02288172, 'SRD': 0.43783457, 'STN': 0.74720746, 'SVC': 1.88615012, 'SYP': 0.1358115, 'SZL': 1, 'THB': 0.49164459, 'TJS': 1.78747221, 'TMT': 4.70248482, 'TND': 5.49513028, 'TOP': 6.86029243, 'TRY': 0.33423861, 'TTD': 2.4280066, 'TVD': 11.51999092, 'TWD': 0.51286141, 'TZS': 0.00627476, 'UAH': 0.3661212, 'UGX': 0.00398507, 'USD': 16.50381355, 'UYU': 0.41062935, 'UZS': 0.00138622, 'VED': 0.01888281, 'VEF': 4.57e-06, 'VES': 0.01888281, 'VND': 0.00063684, 'VUV': 0.13810264, 'WST': 5.91829143, 'XAF': 0.02816492, 'XCD': 6.09271827, 'XDR': 22.3897068, 'XOF': 0.02816492, 'XPF': 0.15482028, 'YER': 0.06988092, 'ZAR': 1, 'ZMW': 0.82589668, 'ZWD': 0.04560317, 'ZWL': 0.00024798}, 'timestamps': {'metal': '2026-10-13T18:05:05.060Z', 'currency': '2026-10-13T18:05:08.995Z'}}

In [4]:
import json

print(json.dumps(data, indent=4))

{
    "status": "success",
    "currency": "ZAR",
    "unit": "toz",
    "metals": {
        "gold": 68516.2421,
        "silver": 975.1443,
        "platinum": 27393.0297,
        "palladium": 18571.8569,
        "lbma_gold_am": 69026.375,
        "lbma_gold_pm": 68812.6506,
        "lbma_silver": 993.6946,
        "lbma_platinum_am": 27761.0648,
        "lbma_platinum_pm": 27874.1159,
        "lbma_palladium_am": 18993.4138,
        "lbma_palladium_pm": 18992.5886,
        "mcx_gold": 80097.3196,
        "mcx_gold_am": 79297.157,
        "mcx_gold_pm": 79388.3438,
        "mcx_silver": 1182.8019,
        "mcx_silver_am": 1182.6237,
        "mcx_silver_pm": 1183.5248,
        "ibja_gold": 79649.6223,
        "ibja_silver": 1181.8315,
        "copper": 7.6576,
        "aluminum": 1.5501,
        "lead": 0.9715,
        "nickel": 7.9619,
        "zinc": 1.8951,
        "lme_copper": 7.5241,
        "lme_aluminum": 1.5708,
        "lme_lead": 0.9676,
        "lme_nickel": 8.0695,
        "lme_zinc": 1.9301
    },
    "currencies": {
        "AED": 4.49389069,
        "AFN": 0.25418233,
        "ALL": 0.20212972,
        "AMD": 0.0455835,
        "ANG": 9.16919216,
        "AOA": 0.01803796,
        "ARS": 0.01090409,
        "AUD": 11.51999092,
        "AWG": 9.22000757,
        "AZN": 9.70812566,
        "BAM": 9.44610438,
        "BBD": 8.25190678,
        "BDT": 0.13402174,
        "BGN": 9.44610438,
        "BHD": 43.89312115,
        "BIF": 0.00550557,
        "BMD": 16.50381355,
        "BND": 12.89409228,
        "BOB": 1.40816775,
        "BRL": 3.29067525,
        "BSD": 16.50381355,
        "BTC": 1370782.78973121,
        "BTN": 0.17347178,
        "BWP": 1.21220098,
        "BYN": 5.50127118,
        "BYR": 0.0006034,
        "BZD": 8.2081929,
        "CAD": 11.60875218,
        "CDF": 0.00714824,
        "CHF": 19.81173906,
        "CLP": 0.0168128,
        "CNH": 2.46568983,
        "CNY": 2.46578026,
        "COP": 0.00517645,
        "CRC": 0.0362445,
        "CUC": 16.50381355,
        "CUP": 0.6876589,
        "CVE": 0.16754307,
        "CZK": 0.75870146,
        "DJF": 0.09265383,
        "DKK": 2.47145376,
        "DOP": 0.26946396,
        "DZD": 0.12266243,
        "EEK": 1.18076305,
        "EGP": 0.31263888,
        "ERN": 1.10025424,
        "ETB": 0.10240573,
        "EUR": 18.47497434,
        "FJD": 7.31848257,
        "FKP": 21.86508804,
        "GBP": 21.86508804,
        "GEL": 6.36575646,
        "GGP": 21.86508804,
        "GHS": 1.41131714,
        "GIP": 21.86508804,
        "GMD": 0.22196621,
        "GNF": 0.00187378,
        "GTQ": 2.1597572,
        "GYD": 0.07889589,
        "HKD": 2.10283204,
        "HNL": 0.61403023,
        "HRK": 2.45205048,
        "HTG": 0.1256659,
        "HUF": 0.05077736,
        "IDR": 0.00092188,
        "ILS": 5.37046298,
        "IMP": 21.86508804,
        "INR": 0.17347178,
        "IQD": 0.01089374,
        "IRR": 9.17e-06,
        "ISK": 0.13559425,
        "JEP": 21.86508804,
        "JMD": 0.10408174,
        "JOD": 23.27759316,
        "JPY": 0.10421579,
        "KES": 0.12722742,
        "KGS": 0.18871016,
        "KHR": 0.00405528,
        "KMF": 0.03755322,
        "KPW": 0.01833476,
        "KRW": 0.01230123,
        "KWD": 53.02146346,
        "KYD": 19.87910744,
        "KZT": 0.03669269,
        "LAK": 0.0007366,
        "LBP": 0.00018339,
        "LKR": 0.04987718,
        "LRD": 0.09646126,
        "LSL": 1,
        "LTL": 5.35072241,
        "LVL": 26.28766981,
        "LYD": 2.56663969,
        "MAD": 1.68276146,
        "MDL": 0.91905425,
        "MGA": 0.00365312,
        "MKD": 0.29992627,
        "MMK": 0.00786,
        "MNT": 0.00458913,
        "MOP": 2.04158451,
        "MRU": 0.41110552,
        "MUR": 0.34621557,
        "MVR": 1.06752014,
        "MWK": 0.00953533,
        "MXN": 0.89777326,
        "MYR": 4.03287211,
        "MZN": 0.25892266,
        "NAD": 1,
        "NGN": 0.01242537,
        "NIO": 0.44837671,
        "NOK": 1.7326185,
        "NPR": 0.10836907,
        "NTD": 0.5565185,
        "NZD": 9.26378366,
        "OMR": 42.89151498,
        "PAB": 16.50381355,
        "PEN": 4.80597264,
        "PGK": 3.7145883,
        "PHP": 0.26292666,
        "PKR": 0.05958469,
        "PLN": 4.22620859,
        "PYG": 0.00288821,
        "QAR": 4.53401471,
        "RON": 3.46014011,
        "RSD": 0.1573632,
        "RUB": 0.19731963,
        "RWF": 0.01118887,
        "SAR": 4.40101695,
        "SBD": 2.04603568,
        "SCR": 1.12392962,
        "SDG": 0.02749894,
        "SEK": 1.65495631,
        "SGD": 12.89409228,
        "SHP": 21.86508804,
        "SKK": 0.6132568,
        "SLE": 0.71912055,
        "SLL": 0.000727,
        "SOS": 0.02890192,
        "SPL": 99.02288172,
        "SRD": 0.43783457,
        "STN": 0.74720746,
        "SVC": 1.88615012,
        "SYP": 0.1358115,
        "SZL": 1,
        "THB": 0.49164459,
        "TJS": 1.78747221,
        "TMT": 4.70248482,
        "TND": 5.49513028,
        "TOP": 6.86029243,
        "TRY": 0.33423861,
        "TTD": 2.4280066,
        "TVD": 11.51999092,
        "TWD": 0.51286141,
        "TZS": 0.00627476,
        "UAH": 0.3661212,
        "UGX": 0.00398507,
        "USD": 16.50381355,
        "UYU": 0.41062935,
        "UZS": 0.00138622,
        "VED": 0.01888281,
        "VEF": 4.57e-06,
        "VES": 0.01888281,
        "VND": 0.00063684,
        "VUV": 0.13810264,
        "WST": 5.91829143,
        "XAF": 0.02816492,
        "XCD": 6.09271827,
        "XDR": 22.3897068,
        "XOF": 0.02816492,
        "XPF": 0.15482028,
        "YER": 0.06988092,
        "ZAR": 1,
        "ZMW": 0.82589668,
        "ZWD": 0.04560317,
        "ZWL": 0.00024798
    },
    "timestamps": {
        "metal": "2026-10-13T18:05:05.060Z",
        "currency": "2026-10-13T18:05:08.995Z"
    }
}

In [ ]:
gold_price = data["metals"]["gold"]
silver_price = data["metals"]["silver"]
platinum_price = data["metals"]["platinum"]
palladium_price = data["metals"]["palladium"]
status_code = data["status"]
currency = data["currency"]
zar = data["unit"]

In [ ]:
print(gold_price)
print(silver_price)
print(status_code)
print(currency)
print(zar)
print("")
print("Gold Price", round(gold_price,2))
print("Silver Price", round(silver_price, 2))
print("Platinum Price", round(platinum_price, 2))
print("Palladium Price", round(palladium_price, 2))

print("")
print("Status Code", status_code)
print("Currency", currency)
print("ZAR", zar)

68878.0415
987.3737
success
ZAR
toz

Gold Price 68878.04
Silver Price 987.37
Platinum Price 27740.17
Palladium Price 18651.72

Status Code success
Currency ZAR
ZAR toz

In [ ]:
for metal in ["gold", "silver", "platinum", "palladium"]:
    price = data["metals"][metal]
    print(metal.title(), "Price", round(price, 2))

Gold Price 68878.04
Silver Price 987.37
Platinum Price 27740.17
Palladium Price 18651.72

In [ ]:
from pprint import pprint

pprint(data["metals"])

pprint(data["metals"].items())

{'aluminum': 1.5575,
 'copper': 7.6879,
 'gold': 68878.0415,
 'ibja_gold': 79694.0998,
 'ibja_silver': 1182.4755,
 'lbma_gold_am': 69015.9927,
 'lbma_gold_pm': 68841.9036,
 'lbma_palladium_am': 18990.557,
 'lbma_palladium_pm': 18989.7319,
 'lbma_platinum_am': 27756.8892,
 'lbma_platinum_pm': 27869.9233,
 'lbma_silver': 993.5452,
 'lead': 0.9734,
 'lme_aluminum': 1.5705,
 'lme_copper': 7.5229,
 'lme_lead': 0.9675,
 'lme_nickel': 8.0683,
 'lme_zinc': 1.9298,
 'mcx_gold': 80488.6339,
 'mcx_gold_am': 79341.435,
 'mcx_gold_pm': 79432.6708,
 'mcx_silver': 1193.5198,
 'mcx_silver_am': 1183.2841,
 'mcx_silver_pm': 1184.185,
 'nickel': 8.0013,
 'palladium': 18651.7187,
 'platinum': 27740.1734,
 'silver': 987.3737,
 'zinc': 1.9269}
dict_items([('gold', 68878.0415), ('silver', 987.3737), ('platinum', 27740.1734), ('palladium', 18651.7187), ('lbma_gold_am', 69015.9927), ('lbma_gold_pm', 68841.9036), ('lbma_silver', 993.5452), ('lbma_platinum_am', 27756.8892), ('lbma_platinum_pm', 27869.9233), ('lbma_palladium_am', 18990.557), ('lbma_palladium_pm', 18989.7319), ('mcx_gold', 80488.6339), ('mcx_gold_am', 79341.435), ('mcx_gold_pm', 79432.6708), ('mcx_silver', 1193.5198), ('mcx_silver_am', 1183.2841), ('mcx_silver_pm', 1184.185), ('ibja_gold', 79694.0998), ('ibja_silver', 1182.4755), ('copper', 7.6879), ('aluminum', 1.5575), ('lead', 0.9734), ('nickel', 8.0013), ('zinc', 1.9269), ('lme_copper', 7.5229), ('lme_aluminum', 1.5705), ('lme_lead', 0.9675), ('lme_nickel', 8.0683), ('lme_zinc', 1.9298)])

In [ ]:
for metal, price in data["metals"].items():
    print(metal.title(),  "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72
Lbma_Gold_Am Price: 69015.99
Lbma_Gold_Pm Price: 68841.9
Lbma_Silver Price: 993.55
Lbma_Platinum_Am Price: 27756.89
Lbma_Platinum_Pm Price: 27869.92
Lbma_Palladium_Am Price: 18990.56
Lbma_Palladium_Pm Price: 18989.73
Mcx_Gold Price: 80488.63
Mcx_Gold_Am Price: 79341.43
Mcx_Gold_Pm Price: 79432.67
Mcx_Silver Price: 1193.52
Mcx_Silver_Am Price: 1183.28
Mcx_Silver_Pm Price: 1184.18
Ibja_Gold Price: 79694.1
Ibja_Silver Price: 1182.48
Copper Price: 7.69
Aluminum Price: 1.56
Lead Price: 0.97
Nickel Price: 8.0
Zinc Price: 1.93
Lme_Copper Price: 7.52
Lme_Aluminum Price: 1.57
Lme_Lead Price: 0.97
Lme_Nickel Price: 8.07
Lme_Zinc Price: 1.93

In [ ]:
for metal, price in data["metals"].items():
    if metal in ["gold", "silver", "platinum", "palladium"]:
        print(metal.title(), "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72

In [ ]:
for metal, price in data["metals"].items():
    if metal in ["gold", "silver", "platinum", "palladium"]:
        print(metal.title(), "Price:", round(price, 2))
    else:
        print(metal.title(), "N/A")

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72
Lbma_Gold_Am N/A
Lbma_Gold_Pm N/A
Lbma_Silver N/A
Lbma_Platinum_Am N/A
Lbma_Platinum_Pm N/A
Lbma_Palladium_Am N/A
Lbma_Palladium_Pm N/A
Mcx_Gold N/A
Mcx_Gold_Am N/A
Mcx_Gold_Pm N/A
Mcx_Silver N/A
Mcx_Silver_Am N/A
Mcx_Silver_Pm N/A
Ibja_Gold N/A
Ibja_Silver N/A
Copper N/A
Aluminum N/A
Lead N/A
Nickel N/A
Zinc N/A
Lme_Copper N/A
Lme_Aluminum N/A
Lme_Lead N/A
Lme_Nickel N/A
Lme_Zinc N/A

In [ ]:
for metal, price in data["metals"].items():
    if metal not in ["gold", "silver", "platinum", "palladium"]:
        continue

    print(metal.title(), "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72

In [ ]:
for metal, price in data["metals"].items():
    if price <= 2000:
        print("Under 2000!", metal, round(price, 2))
    elif price < 50000:
        print("Between 2000 and 50000!",metal, round(price, 2))
    elif price >= 50000:
        print("Over 50000!",metal, round(price, 2))
    else: print("?????",metal, round(price, 2))

Over 50000! gold 68878.04
Under 2000! silver 987.37
Between 2000 and 50000! platinum 27740.17
Between 2000 and 50000! palladium 18651.72
Over 50000! lbma_gold_am 69015.99
Over 50000! lbma_gold_pm 68841.9
Under 2000! lbma_silver 993.55
Between 2000 and 50000! lbma_platinum_am 27756.89
Between 2000 and 50000! lbma_platinum_pm 27869.92
Between 2000 and 50000! lbma_palladium_am 18990.56
Between 2000 and 50000! lbma_palladium_pm 18989.73
Over 50000! mcx_gold 80488.63
Over 50000! mcx_gold_am 79341.43
Over 50000! mcx_gold_pm 79432.67
Under 2000! mcx_silver 1193.52
Under 2000! mcx_silver_am 1183.28
Under 2000! mcx_silver_pm 1184.18
Over 50000! ibja_gold 79694.1
Under 2000! ibja_silver 1182.48
Under 2000! copper 7.69
Under 2000! aluminum 1.56
Under 2000! lead 0.97
Under 2000! nickel 8.0
Under 2000! zinc 1.93
Under 2000! lme_copper 7.52
Under 2000! lme_aluminum 1.57
Under 2000! lme_lead 0.97
Under 2000! lme_nickel 8.07
Under 2000! lme_zinc 1.93

In [ ]:
for metal, price in data["metals"].items():
    if price <= 2000:
        print("Under 2000!", metal, round(price, 2))

    else:
        if price >= 50000:
            print("Over 50000!", metal, round(price, 2))
        else:
            print("Between 2000 and 50000!", metal, round(price, 2))

Over 50000! gold 68878.04
Under 2000! silver 987.37
Between 2000 and 50000! platinum 27740.17
Between 2000 and 50000! palladium 18651.72
Over 50000! lbma_gold_am 69015.99
Over 50000! lbma_gold_pm 68841.9
Under 2000! lbma_silver 993.55
Between 2000 and 50000! lbma_platinum_am 27756.89
Between 2000 and 50000! lbma_platinum_pm 27869.92
Between 2000 and 50000! lbma_palladium_am 18990.56
Between 2000 and 50000! lbma_palladium_pm 18989.73
Over 50000! mcx_gold 80488.63
Over 50000! mcx_gold_am 79341.43
Over 50000! mcx_gold_pm 79432.67
Under 2000! mcx_silver 1193.52
Under 2000! mcx_silver_am 1183.28
Under 2000! mcx_silver_pm 1184.18
Over 50000! ibja_gold 79694.1
Under 2000! ibja_silver 1182.48
Under 2000! copper 7.69
Under 2000! aluminum 1.56
Under 2000! lead 0.97
Under 2000! nickel 8.0
Under 2000! zinc 1.93
Under 2000! lme_copper 7.52
Under 2000! lme_aluminum 1.57
Under 2000! lme_lead 0.97
Under 2000! lme_nickel 8.07
Under 2000! lme_zinc 1.93

In [ ]:
for metal, price in data["metals"].items():
    if metal == "gold":
        if price > 50000:
            print("Gold is expensive!")
        else:
            print("Gold is below 50000")
    if metal == "silver":
        if price > 1200:
            print("Silver is expensive!")
        else:
            print("Silver is Cheap!")

Gold is expensive!
Silver is Cheap!

In [35]:

import pandas as pd

In [36]:
df = pd.DataFrame(data["metals"].items())
df.columns = ["Metal", "Price"]

print(df.head())
df

          Metal       Price
0          gold  68516.2421
1        silver    975.1443
2      platinum  27393.0297
3     palladium  18571.8569
4  lbma_gold_am  69026.3750

                Metal       Price
0                gold  68516.2421
1              silver    975.1443
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Metal   29 non-null     object
 1   Price   29 non-null     float64
dtypes: float64(1), object(1)
memory usage: 596.0+ bytes

In [8]:
df["Price"]

0     68516.2421
1       975.1443
2     27393.0297
3     18571.8569
4     69026.3750
5     68812.6506
6       993.6946
7     27761.0648
8     27874.1159
9     18993.4138
10    18992.5886
11    80097.3196
12    79297.1570
13    79388.3438
14     1182.8019
15     1182.6237
16     1183.5248
17    79649.6223
18     1181.8315
19        7.6576
20        1.5501
21        0.9715
22        7.9619
23        1.8951
24        7.5241
25        1.5708
26        0.9676
27        8.0695
28        1.9301
Name: Price, dtype: float64

In [9]:
df[["Metal", "Price"]]

                Metal       Price
0                gold  68516.2421
1              silver    975.1443
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [ ]:
print(type(df["Price"]))
print(type(df[["Price"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [10]:
df[df["Metal"] == "gold"]

  Metal       Price
0  gold  68516.2421

In [13]:
df["Metal"] == "gold"

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
Name: Metal, dtype: bool

In [14]:
df[df["Price"] > 20000]

               Metal       Price
0               gold  68516.2421
2           platinum  27393.0297
4       lbma_gold_am  69026.3750
5       lbma_gold_pm  68812.6506
7   lbma_platinum_am  27761.0648
8   lbma_platinum_pm  27874.1159
11          mcx_gold  80097.3196
12       mcx_gold_am  79297.1570
13       mcx_gold_pm  79388.3438
17         ibja_gold  79649.6223

In [16]:
df[(df["Price"] > 1000) & (df["Price"] < 30000)]
df[df["Price"].between(1000, 30000)]

                Metal       Price
2            platinum  27393.0297
3           palladium  18571.8569
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
18        ibja_silver   1181.8315

In [17]:
df[df["Price"].between(10000, 50000)]

                Metal       Price
2            platinum  27393.0297
3           palladium  18571.8569
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886

In [20]:
df[~df["Metal"].isin(["gold", "silver"])]

                Metal       Price
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [27]:
df.sort_values("Price", ascending=False)

                Metal       Price
11           mcx_gold  80097.3196
17          ibja_gold  79649.6223
13        mcx_gold_pm  79388.3438
12        mcx_gold_am  79297.1570
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
0                gold  68516.2421
8    lbma_platinum_pm  27874.1159
7    lbma_platinum_am  27761.0648
2            platinum  27393.0297
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
3           palladium  18571.8569
16      mcx_silver_pm   1183.5248
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
18        ibja_silver   1181.8315
6         lbma_silver    993.6946
1              silver    975.1443
27         lme_nickel      8.0695
22             nickel      7.9619
19             copper      7.6576
24         lme_copper      7.5241
28           lme_zinc      1.9301
23               zinc      1.8951
25       lme_aluminum      1.5708
20           aluminum      1.5501
21               lead      0.9715
26           lme_lead      0.9676

In [31]:
df.sort_values("Metal", ascending=True)

                Metal       Price
20           aluminum      1.5501
19             copper      7.6576
0                gold  68516.2421
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
6         lbma_silver    993.6946
21               lead      0.9715
25       lme_aluminum      1.5708
24         lme_copper      7.5241
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
22             nickel      7.9619
3           palladium  18571.8569
2            platinum  27393.0297
1              silver    975.1443
23               zinc      1.8951

In [33]:
df["Price_Up_10%"] = df["Price"] * 1.10
df

                Metal       Price  Price_Up_10%
0                gold  68516.2421   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [37]:
df

                Metal       Price
0                gold  68516.2421
1              silver    975.1443
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [39]:
df_original = df.copy()
df_original

                Metal       Price
0                gold  68516.2421
1              silver    975.1443
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [40]:
df["Price_Up_10%"] = df["Price"] * 1.10
df

                Metal       Price  Price_Up_10%
0                gold  68516.2421   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [42]:
df = df.rename(columns={"Price": "Price_ZAR"})
df

                Metal   Price_ZAR  Price_Up_10%
0                gold  68516.2421   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [45]:
df = df.rename(columns={"Metal": "Metal_Name", "Price_Up_10%": "Price_10%_Up"})
df

           Metal_Name   Price_ZAR  Price_10%_Up
0                gold  68516.2421   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [46]:
df.isna().sum()

Metal_Name      0
Price_ZAR       0
Price_10%_Up    0
dtype: int64

In [47]:
df_test = df.copy()

df_test.loc[0, "Price_ZAR"] = None

df_test

           Metal_Name   Price_ZAR  Price_10%_Up
0                gold         NaN   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [48]:
df_test.isna().sum()

Metal_Name      0
Price_ZAR       1
Price_10%_Up    0
dtype: int64

In [49]:
df_test["Price_ZAR"] = df_test["Price_ZAR"].fillna(0)

df_test

           Metal_Name   Price_ZAR  Price_10%_Up
0                gold      0.0000   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [50]:
df_test["Price_10%_Up"] = df_test["Price_ZAR"] * 1.10

df_test

           Metal_Name   Price_ZAR  Price_10%_Up
0                gold      0.0000       0.00000
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [53]:

df_test = df.copy()
#df_test

df_test.loc[0, "Price_ZAR"] = None
#df_test

df_test = df_test.dropna(subset=["Price_ZAR"])

df_test

           Metal_Name   Price_ZAR  Price_10%_Up
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [55]:
df_test = df_test.reset_index(drop=True)
df_test

           Metal_Name   Price_ZAR  Price_10%_Up
0              silver    975.1443    1072.65873
1            platinum  27393.0297   30132.33267
2           palladium  18571.8569   20429.04259
3        lbma_gold_am  69026.3750   75929.01250
4        lbma_gold_pm  68812.6506   75693.91566
5         lbma_silver    993.6946    1093.06406
6    lbma_platinum_am  27761.0648   30537.17128
7    lbma_platinum_pm  27874.1159   30661.52749
8   lbma_palladium_am  18993.4138   20892.75518
9   lbma_palladium_pm  18992.5886   20891.84746
10           mcx_gold  80097.3196   88107.05156
11        mcx_gold_am  79297.1570   87226.87270
12        mcx_gold_pm  79388.3438   87327.17818
13         mcx_silver   1182.8019    1301.08209
14      mcx_silver_am   1182.6237    1300.88607
15      mcx_silver_pm   1183.5248    1301.87728
16          ibja_gold  79649.6223   87614.58453
17        ibja_silver   1181.8315    1300.01465
18             copper      7.6576       8.42336
19           aluminum      1.5501       1.70511
20               lead      0.9715       1.06865
21             nickel      7.9619       8.75809
22               zinc      1.8951       2.08461
23         lme_copper      7.5241       8.27651
24       lme_aluminum      1.5708       1.72788
25           lme_lead      0.9676       1.06436
26         lme_nickel      8.0695       8.87645
27           lme_zinc      1.9301       2.12311