<a href="https://colab.research.google.com/github/Otto-C/Otto-C.github.io/blob/main/01_Bullion_API_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata

api_key = userdata.get('METALS_API_KEY')

print("API key loaded successfully!" if api_key else "API key not found")

API key loaded successfully!

In [2]:
import requests
url = 'https://api.metals.dev/v1/latest'

params = {
    "api_key": api_key,
    "currency": "ZAR",
    "unit": "toz"
}

response = requests.get(url, params=params, timeout=30)

print("HTTP Status", response.status_code)
print("API Status", response.json().get("status"))

HTTP Status 200
API Status success

In [3]:
data = response.json()
print(data)

{'status': 'success', 'currency': 'ZAR', 'unit': 'toz', 'metals': {'gold': 66288.1529, 'silver': 894.3596, 'platinum': 25718.7673, 'palladium': 17285.7485, 'lbma_gold_am': 66792.4928, 'lbma_gold_pm': 66570.2216, 'lbma_silver': 894.061, 'lbma_platinum_am': 25875.5182, 'lbma_platinum_pm': 25853.1252, 'lbma_palladium_am': 17567.7178, 'lbma_palladium_pm': 17498.8801, 'mcx_gold': 77182.1217, 'mcx_gold_am': 76606.0695, 'mcx_gold_pm': 76642.4788, 'mcx_silver': 1063.624, 'mcx_silver_am': 1056.3637, 'mcx_silver_pm': 1055.2059, 'ibja_gold': 76968.1011, 'ibja_silver': 1056.5147, 'copper': 7.4691, 'aluminum': 1.5613, 'lead': 0.9775, 'nickel': 8.1596, 'zinc': 1.9317, 'lme_copper': 7.3623, 'lme_aluminum': 1.5571, 'lme_lead': 0.9844, 'lme_nickel': 8.2032, 'lme_zinc': 1.9223}, 'currencies': {'AED': 4.51665141, 'AFN': 0.25536951, 'ALL': 0.20474131, 'AMD': 0.04594086, 'ANG': 9.23253182, 'AOA': 0.01801268, 'ARS': 0.01086523, 'AUD': 11.66975455, 'AWG': 9.2667052, 'AZN': 9.75729547, 'BAM': 9.50910881, 'BBD': 8.29370115, 'BDT': 0.13419543, 'BGN': 9.50910881, 'BHD': 44.11543165, 'BIF': 0.0055303, 'BMD': 16.5874023, 'BND': 12.97756256, 'BOB': 1.39807281, 'BRL': 3.3123301, 'BSD': 16.5874023, 'BTC': 1337877.15247717, 'BTN': 0.17472137, 'BWP': 1.2014934, 'BYN': 5.66122945, 'BYR': 0.00060645, 'BZD': 8.22407026, 'CAD': 11.84458634, 'CDF': 0.00717724, 'CHF': 20.10525019, 'CLP': 0.01666611, 'CNH': 2.48664311, 'CNY': 2.4859441, 'COP': 0.00528199, 'CRC': 0.03640711, 'CUC': 16.5874023, 'CUP': 0.69114176, 'CVE': 0.16866056, 'CZK': 0.76391183, 'DJF': 0.09311494, 'DKK': 2.48632885, 'DOP': 0.27082263, 'DZD': 0.12271993, 'EEK': 1.1886386, 'EGP': 0.29716685, 'ERN': 1.10582682, 'ETB': 0.10235396, 'EUR': 18.59820028, 'FJD': 7.39984534, 'FKP': 22.18768977, 'GBP': 22.18768977, 'GEL': 6.39047794, 'GGP': 22.18768977, 'GHS': 1.42903787, 'GIP': 22.18768977, 'GMD': 0.22187422, 'GNF': 0.00187411, 'GTQ': 2.1698483, 'GYD': 0.07916956, 'HKD': 2.11516712, 'HNL': 0.61748004, 'HRK': 2.46840537, 'HTG': 0.12520595, 'HUF': 0.05067682, 'IDR': 0.00092128, 'ILS': 5.34206904, 'IMP': 22.18768977, 'INR': 0.17472137, 'IQD': 0.01098074, 'IRR': 9e-06, 'ISK': 0.13623859, 'JEP': 22.18768977, 'JMD': 0.10459768, 'JOD': 23.39548984, 'JPY': 0.1057538, 'KES': 0.12775411, 'KGS': 0.18966389, 'KHR': 0.00406486, 'KMF': 0.0378037, 'KPW': 0.01842762, 'KRW': 0.01253072, 'KWD': 53.52664141, 'KYD': 20.02075225, 'KZT': 0.03663974, 'LAK': 0.00074187, 'LBP': 0.00018398, 'LKR': 0.04994726, 'LRD': 0.09732538, 'LSL': 1, 'LTL': 5.38641111, 'LVL': 26.46300552, 'LYD': 2.58980607, 'MAD': 1.69085854, 'MDL': 0.92321129, 'MGA': 0.0036167, 'MKD': 0.3022017, 'MMK': 0.00789898, 'MNT': 0.00460856, 'MOP': 2.05356031, 'MRU': 0.41246755, 'MUR': 0.35176831, 'MVR': 1.07292382, 'MWK': 0.00957011, 'MXN': 0.88887183, 'MYR': 4.06041167, 'MZN': 0.2605866, 'NAD': 1, 'NGN': 0.01230659, 'NIO': 0.45103688, 'NOK': 1.77808942, 'NPR': 0.10914969, 'NTD': 0.55933716, 'NZD': 9.45518007, 'OMR': 43.08422189, 'PAB': 16.5874023, 'PEN': 4.81532658, 'PGK': 3.81843261, 'PHP': 0.26080927, 'PKR': 0.05996649, 'PLN': 4.22041959, 'PYG': 0.00287041, 'QAR': 4.55697865, 'RON': 3.47386374, 'RSD': 0.15801619, 'RUB': 0.20566966, 'RWF': 0.01124041, 'SAR': 4.42330728, 'SBD': 2.05898421, 'SCR': 1.1086861, 'SDG': 0.02763753, 'SEK': 1.67042295, 'SGD': 12.97756256, 'SHP': 22.18768977, 'SKK': 0.61734715, 'SLE': 0.7235548, 'SLL': 0.00073069, 'SOS': 0.02902527, 'SPL': 99.5244142, 'SRD': 0.44088005, 'STN': 0.75243948, 'SVC': 1.89570312, 'SYP': 0.13652183, 'SZL': 1, 'THB': 0.49196566, 'TJS': 1.8006888, 'TMT': 4.72155111, 'TND': 5.54504021, 'TOP': 6.95164948, 'TRY': 0.33361235, 'TTD': 2.44950999, 'TVD': 11.66975455, 'TWD': 0.50885395, 'TZS': 0.0062862, 'UAH': 0.36662595, 'UGX': 0.00375644, 'USD': 16.5874023, 'UYU': 0.41342043, 'UZS': 0.00139958, 'VED': 0.01875892, 'VEF': 4.6e-06, 'VES': 0.01875892, 'VND': 0.00064187, 'VUV': 0.13978086, 'WST': 5.99301006, 'XAF': 0.02835277, 'XCD': 6.12385117, 'XDR': 22.73314485, 'XOF': 0.02835277, 'XPF': 0.15585292, 'YER': 0.07022968, 'ZAR': 1, 'ZMW': 0.82188391, 'ZWD': 0.04583414, 'ZWL': 0.00024871}, 'timestamps': {'metal': '2026-10-25T17:35:07.031Z', 'currency': '2026-10-25T17:34:12.003Z'}}

In [4]:
import json
from pprint import pprint
import pandas as pd
df = pd.DataFrame(data["metals"].items())
df.columns = ["Metal", "Price"]

#print(df.head())
#df



#print(json.dumps(data, indent=4))

In [ ]:
gold_price = data["metals"]["gold"]
silver_price = data["metals"]["silver"]
platinum_price = data["metals"]["platinum"]
palladium_price = data["metals"]["palladium"]
status_code = data["status"]
currency = data["currency"]
zar = data["unit"]

In [ ]:
print(gold_price)
print(silver_price)
print(status_code)
print(currency)
print(zar)
print("")
print("Gold Price", round(gold_price,2))
print("Silver Price", round(silver_price, 2))
print("Platinum Price", round(platinum_price, 2))
print("Palladium Price", round(palladium_price, 2))

print("")
print("Status Code", status_code)
print("Currency", currency)
print("ZAR", zar)

68878.0415
987.3737
success
ZAR
toz

Gold Price 68878.04
Silver Price 987.37
Platinum Price 27740.17
Palladium Price 18651.72

Status Code success
Currency ZAR
ZAR toz

In [ ]:
for metal in ["gold", "silver", "platinum", "palladium"]:
    price = data["metals"][metal]
    print(metal.title(), "Price", round(price, 2))

Gold Price 68878.04
Silver Price 987.37
Platinum Price 27740.17
Palladium Price 18651.72

In [ ]:
from pprint import pprint

pprint(data["metals"])

pprint(data["metals"].items())

{'aluminum': 1.5575,
 'copper': 7.6879,
 'gold': 68878.0415,
 'ibja_gold': 79694.0998,
 'ibja_silver': 1182.4755,
 'lbma_gold_am': 69015.9927,
 'lbma_gold_pm': 68841.9036,
 'lbma_palladium_am': 18990.557,
 'lbma_palladium_pm': 18989.7319,
 'lbma_platinum_am': 27756.8892,
 'lbma_platinum_pm': 27869.9233,
 'lbma_silver': 993.5452,
 'lead': 0.9734,
 'lme_aluminum': 1.5705,
 'lme_copper': 7.5229,
 'lme_lead': 0.9675,
 'lme_nickel': 8.0683,
 'lme_zinc': 1.9298,
 'mcx_gold': 80488.6339,
 'mcx_gold_am': 79341.435,
 'mcx_gold_pm': 79432.6708,
 'mcx_silver': 1193.5198,
 'mcx_silver_am': 1183.2841,
 'mcx_silver_pm': 1184.185,
 'nickel': 8.0013,
 'palladium': 18651.7187,
 'platinum': 27740.1734,
 'silver': 987.3737,
 'zinc': 1.9269}
dict_items([('gold', 68878.0415), ('silver', 987.3737), ('platinum', 27740.1734), ('palladium', 18651.7187), ('lbma_gold_am', 69015.9927), ('lbma_gold_pm', 68841.9036), ('lbma_silver', 993.5452), ('lbma_platinum_am', 27756.8892), ('lbma_platinum_pm', 27869.9233), ('lbma_palladium_am', 18990.557), ('lbma_palladium_pm', 18989.7319), ('mcx_gold', 80488.6339), ('mcx_gold_am', 79341.435), ('mcx_gold_pm', 79432.6708), ('mcx_silver', 1193.5198), ('mcx_silver_am', 1183.2841), ('mcx_silver_pm', 1184.185), ('ibja_gold', 79694.0998), ('ibja_silver', 1182.4755), ('copper', 7.6879), ('aluminum', 1.5575), ('lead', 0.9734), ('nickel', 8.0013), ('zinc', 1.9269), ('lme_copper', 7.5229), ('lme_aluminum', 1.5705), ('lme_lead', 0.9675), ('lme_nickel', 8.0683), ('lme_zinc', 1.9298)])

In [ ]:
for metal, price in data["metals"].items():
    print(metal.title(),  "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72
Lbma_Gold_Am Price: 69015.99
Lbma_Gold_Pm Price: 68841.9
Lbma_Silver Price: 993.55
Lbma_Platinum_Am Price: 27756.89
Lbma_Platinum_Pm Price: 27869.92
Lbma_Palladium_Am Price: 18990.56
Lbma_Palladium_Pm Price: 18989.73
Mcx_Gold Price: 80488.63
Mcx_Gold_Am Price: 79341.43
Mcx_Gold_Pm Price: 79432.67
Mcx_Silver Price: 1193.52
Mcx_Silver_Am Price: 1183.28
Mcx_Silver_Pm Price: 1184.18
Ibja_Gold Price: 79694.1
Ibja_Silver Price: 1182.48
Copper Price: 7.69
Aluminum Price: 1.56
Lead Price: 0.97
Nickel Price: 8.0
Zinc Price: 1.93
Lme_Copper Price: 7.52
Lme_Aluminum Price: 1.57
Lme_Lead Price: 0.97
Lme_Nickel Price: 8.07
Lme_Zinc Price: 1.93

In [ ]:
for metal, price in data["metals"].items():
    if metal in ["gold", "silver", "platinum", "palladium"]:
        print(metal.title(), "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72

In [ ]:
for metal, price in data["metals"].items():
    if metal in ["gold", "silver", "platinum", "palladium"]:
        print(metal.title(), "Price:", round(price, 2))
    else:
        print(metal.title(), "N/A")

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72
Lbma_Gold_Am N/A
Lbma_Gold_Pm N/A
Lbma_Silver N/A
Lbma_Platinum_Am N/A
Lbma_Platinum_Pm N/A
Lbma_Palladium_Am N/A
Lbma_Palladium_Pm N/A
Mcx_Gold N/A
Mcx_Gold_Am N/A
Mcx_Gold_Pm N/A
Mcx_Silver N/A
Mcx_Silver_Am N/A
Mcx_Silver_Pm N/A
Ibja_Gold N/A
Ibja_Silver N/A
Copper N/A
Aluminum N/A
Lead N/A
Nickel N/A
Zinc N/A
Lme_Copper N/A
Lme_Aluminum N/A
Lme_Lead N/A
Lme_Nickel N/A
Lme_Zinc N/A

In [ ]:
for metal, price in data["metals"].items():
    if metal not in ["gold", "silver", "platinum", "palladium"]:
        continue

    print(metal.title(), "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72

In [ ]:
for metal, price in data["metals"].items():
    if price <= 2000:
        print("Under 2000!", metal, round(price, 2))
    elif price < 50000:
        print("Between 2000 and 50000!",metal, round(price, 2))
    elif price >= 50000:
        print("Over 50000!",metal, round(price, 2))
    else: print("?????",metal, round(price, 2))

Over 50000! gold 68878.04
Under 2000! silver 987.37
Between 2000 and 50000! platinum 27740.17
Between 2000 and 50000! palladium 18651.72
Over 50000! lbma_gold_am 69015.99
Over 50000! lbma_gold_pm 68841.9
Under 2000! lbma_silver 993.55
Between 2000 and 50000! lbma_platinum_am 27756.89
Between 2000 and 50000! lbma_platinum_pm 27869.92
Between 2000 and 50000! lbma_palladium_am 18990.56
Between 2000 and 50000! lbma_palladium_pm 18989.73
Over 50000! mcx_gold 80488.63
Over 50000! mcx_gold_am 79341.43
Over 50000! mcx_gold_pm 79432.67
Under 2000! mcx_silver 1193.52
Under 2000! mcx_silver_am 1183.28
Under 2000! mcx_silver_pm 1184.18
Over 50000! ibja_gold 79694.1
Under 2000! ibja_silver 1182.48
Under 2000! copper 7.69
Under 2000! aluminum 1.56
Under 2000! lead 0.97
Under 2000! nickel 8.0
Under 2000! zinc 1.93
Under 2000! lme_copper 7.52
Under 2000! lme_aluminum 1.57
Under 2000! lme_lead 0.97
Under 2000! lme_nickel 8.07
Under 2000! lme_zinc 1.93

In [ ]:
for metal, price in data["metals"].items():
    if price <= 2000:
        print("Under 2000!", metal, round(price, 2))

    else:
        if price >= 50000:
            print("Over 50000!", metal, round(price, 2))
        else:
            print("Between 2000 and 50000!", metal, round(price, 2))

Over 50000! gold 68878.04
Under 2000! silver 987.37
Between 2000 and 50000! platinum 27740.17
Between 2000 and 50000! palladium 18651.72
Over 50000! lbma_gold_am 69015.99
Over 50000! lbma_gold_pm 68841.9
Under 2000! lbma_silver 993.55
Between 2000 and 50000! lbma_platinum_am 27756.89
Between 2000 and 50000! lbma_platinum_pm 27869.92
Between 2000 and 50000! lbma_palladium_am 18990.56
Between 2000 and 50000! lbma_palladium_pm 18989.73
Over 50000! mcx_gold 80488.63
Over 50000! mcx_gold_am 79341.43
Over 50000! mcx_gold_pm 79432.67
Under 2000! mcx_silver 1193.52
Under 2000! mcx_silver_am 1183.28
Under 2000! mcx_silver_pm 1184.18
Over 50000! ibja_gold 79694.1
Under 2000! ibja_silver 1182.48
Under 2000! copper 7.69
Under 2000! aluminum 1.56
Under 2000! lead 0.97
Under 2000! nickel 8.0
Under 2000! zinc 1.93
Under 2000! lme_copper 7.52
Under 2000! lme_aluminum 1.57
Under 2000! lme_lead 0.97
Under 2000! lme_nickel 8.07
Under 2000! lme_zinc 1.93

In [ ]:
for metal, price in data["metals"].items():
    if metal == "gold":
        if price > 50000:
            print("Gold is expensive!")
        else:
            print("Gold is below 50000")
    if metal == "silver":
        if price > 1200:
            print("Silver is expensive!")
        else:
            print("Silver is Cheap!")

Gold is expensive!
Silver is Cheap!

In [ ]:

import pandas as pd

In [ ]:
df = pd.DataFrame(data["metals"].items())
df.columns = ["Metal", "Price"]

print(df.head())
df

          Metal       Price
0          gold  68698.4984
1        silver    939.8753
2      platinum  27133.9058
3     palladium  18329.6583
4  lbma_gold_am  68958.5420

                Metal       Price
0                gold  68698.4984
1              silver    939.8753
2            platinum  27133.9058
3           palladium  18329.6583
4        lbma_gold_am  68958.5420
5        lbma_gold_pm  69078.9172
6         lbma_silver    951.5418
7    lbma_platinum_am  26954.9919
8    lbma_platinum_pm  27041.5632
9   lbma_palladium_am  18682.0776
10  lbma_palladium_pm  18609.5226
11           mcx_gold  79792.3298
12        mcx_gold_am  78827.2779
13        mcx_gold_pm  78700.5112
14         mcx_silver   1139.2184
15      mcx_silver_am   1138.6198
16      mcx_silver_pm   1136.3986
17          ibja_gold  78989.7862
18        ibja_silver   1137.7953
19             copper      7.4884
20           aluminum      1.5347
21               lead      0.9620
22             nickel      7.8716
23               zinc      1.8865
24         lme_copper      7.4292
25       lme_aluminum      1.5448
26           lme_lead      0.9699
27         lme_nickel      7.8754
28           lme_zinc      1.8972

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Metal   29 non-null     object
 1   Price   29 non-null     float64
dtypes: float64(1), object(1)
memory usage: 596.0+ bytes

In [ ]:
df["Price"]

0     68516.2421
1       975.1443
2     27393.0297
3     18571.8569
4     69026.3750
5     68812.6506
6       993.6946
7     27761.0648
8     27874.1159
9     18993.4138
10    18992.5886
11    80097.3196
12    79297.1570
13    79388.3438
14     1182.8019
15     1182.6237
16     1183.5248
17    79649.6223
18     1181.8315
19        7.6576
20        1.5501
21        0.9715
22        7.9619
23        1.8951
24        7.5241
25        1.5708
26        0.9676
27        8.0695
28        1.9301
Name: Price, dtype: float64

In [ ]:
df[["Metal", "Price"]]

                Metal       Price
0                gold  68516.2421
1              silver    975.1443
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [ ]:
print(type(df["Price"]))
print(type(df[["Price"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
df[df["Metal"] == "gold"]

  Metal       Price
0  gold  68516.2421

In [ ]:
df["Metal"] == "gold"

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
Name: Metal, dtype: bool

In [ ]:
df[df["Price"] > 20000]

               Metal       Price
0               gold  68516.2421
2           platinum  27393.0297
4       lbma_gold_am  69026.3750
5       lbma_gold_pm  68812.6506
7   lbma_platinum_am  27761.0648
8   lbma_platinum_pm  27874.1159
11          mcx_gold  80097.3196
12       mcx_gold_am  79297.1570
13       mcx_gold_pm  79388.3438
17         ibja_gold  79649.6223

In [ ]:
df[(df["Price"] > 1000) & (df["Price"] < 30000)]
df[df["Price"].between(1000, 30000)]

                Metal       Price
2            platinum  27393.0297
3           palladium  18571.8569
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
18        ibja_silver   1181.8315

In [ ]:
df[df["Price"].between(10000, 50000)]

                Metal       Price
2            platinum  27393.0297
3           palladium  18571.8569
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886

In [ ]:
df[~df["Metal"].isin(["gold", "silver"])]

                Metal       Price
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [ ]:
df.sort_values("Price", ascending=False)

                Metal       Price
11           mcx_gold  80097.3196
17          ibja_gold  79649.6223
13        mcx_gold_pm  79388.3438
12        mcx_gold_am  79297.1570
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
0                gold  68516.2421
8    lbma_platinum_pm  27874.1159
7    lbma_platinum_am  27761.0648
2            platinum  27393.0297
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
3           palladium  18571.8569
16      mcx_silver_pm   1183.5248
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
18        ibja_silver   1181.8315
6         lbma_silver    993.6946
1              silver    975.1443
27         lme_nickel      8.0695
22             nickel      7.9619
19             copper      7.6576
24         lme_copper      7.5241
28           lme_zinc      1.9301
23               zinc      1.8951
25       lme_aluminum      1.5708
20           aluminum      1.5501
21               lead      0.9715
26           lme_lead      0.9676

In [ ]:
df.sort_values("Metal", ascending=True)

                Metal       Price
20           aluminum      1.5501
19             copper      7.6576
0                gold  68516.2421
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
6         lbma_silver    993.6946
21               lead      0.9715
25       lme_aluminum      1.5708
24         lme_copper      7.5241
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
22             nickel      7.9619
3           palladium  18571.8569
2            platinum  27393.0297
1              silver    975.1443
23               zinc      1.8951

In [ ]:
df["Price_Up_10%"] = df["Price"] * 1.10
df

                Metal       Price  Price_Up_10%
0                gold  68516.2421   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [ ]:
df

                Metal       Price
0                gold  68516.2421
1              silver    975.1443
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [ ]:
df_original = df.copy()
df_original

                Metal       Price
0                gold  68516.2421
1              silver    975.1443
2            platinum  27393.0297
3           palladium  18571.8569
4        lbma_gold_am  69026.3750
5        lbma_gold_pm  68812.6506
6         lbma_silver    993.6946
7    lbma_platinum_am  27761.0648
8    lbma_platinum_pm  27874.1159
9   lbma_palladium_am  18993.4138
10  lbma_palladium_pm  18992.5886
11           mcx_gold  80097.3196
12        mcx_gold_am  79297.1570
13        mcx_gold_pm  79388.3438
14         mcx_silver   1182.8019
15      mcx_silver_am   1182.6237
16      mcx_silver_pm   1183.5248
17          ibja_gold  79649.6223
18        ibja_silver   1181.8315
19             copper      7.6576
20           aluminum      1.5501
21               lead      0.9715
22             nickel      7.9619
23               zinc      1.8951
24         lme_copper      7.5241
25       lme_aluminum      1.5708
26           lme_lead      0.9676
27         lme_nickel      8.0695
28           lme_zinc      1.9301

In [ ]:
df["Price_Up_10%"] = df["Price"] * 1.10
df

                Metal       Price  Price_Up_10%
0                gold  68516.2421   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [ ]:
df = df.rename(columns={"Price": "Price_ZAR"})
df

                Metal   Price_ZAR  Price_Up_10%
0                gold  68516.2421   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [ ]:
df = df.rename(columns={"Metal": "Metal_Name", "Price_Up_10%": "Price_10%_Up"})
df

           Metal_Name   Price_ZAR  Price_10%_Up
0                gold  68516.2421   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [ ]:
df.isna().sum()

Metal_Name      0
Price_ZAR       0
Price_10%_Up    0
dtype: int64

In [ ]:
df_test = df.copy()

df_test.loc[0, "Price_ZAR"] = None

df_test

           Metal_Name   Price_ZAR  Price_10%_Up
0                gold         NaN   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [ ]:
df_test.isna().sum()

Metal_Name      0
Price_ZAR       1
Price_10%_Up    0
dtype: int64

In [ ]:
df_test["Price_ZAR"] = df_test["Price_ZAR"].fillna(0)

df_test

           Metal_Name   Price_ZAR  Price_10%_Up
0                gold      0.0000   75367.86631
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [ ]:
df_test["Price_10%_Up"] = df_test["Price_ZAR"] * 1.10

df_test

           Metal_Name   Price_ZAR  Price_10%_Up
0                gold      0.0000       0.00000
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [ ]:

df_test = df.copy()
#df_test

df_test.loc[0, "Price_ZAR"] = None
#df_test

df_test = df_test.dropna(subset=["Price_ZAR"])

df_test

           Metal_Name   Price_ZAR  Price_10%_Up
1              silver    975.1443    1072.65873
2            platinum  27393.0297   30132.33267
3           palladium  18571.8569   20429.04259
4        lbma_gold_am  69026.3750   75929.01250
5        lbma_gold_pm  68812.6506   75693.91566
6         lbma_silver    993.6946    1093.06406
7    lbma_platinum_am  27761.0648   30537.17128
8    lbma_platinum_pm  27874.1159   30661.52749
9   lbma_palladium_am  18993.4138   20892.75518
10  lbma_palladium_pm  18992.5886   20891.84746
11           mcx_gold  80097.3196   88107.05156
12        mcx_gold_am  79297.1570   87226.87270
13        mcx_gold_pm  79388.3438   87327.17818
14         mcx_silver   1182.8019    1301.08209
15      mcx_silver_am   1182.6237    1300.88607
16      mcx_silver_pm   1183.5248    1301.87728
17          ibja_gold  79649.6223   87614.58453
18        ibja_silver   1181.8315    1300.01465
19             copper      7.6576       8.42336
20           aluminum      1.5501       1.70511
21               lead      0.9715       1.06865
22             nickel      7.9619       8.75809
23               zinc      1.8951       2.08461
24         lme_copper      7.5241       8.27651
25       lme_aluminum      1.5708       1.72788
26           lme_lead      0.9676       1.06436
27         lme_nickel      8.0695       8.87645
28           lme_zinc      1.9301       2.12311

In [ ]:
df_test = df_test.reset_index(drop=True)
df_test

           Metal_Name   Price_ZAR  Price_10%_Up
0              silver    975.1443    1072.65873
1            platinum  27393.0297   30132.33267
2           palladium  18571.8569   20429.04259
3        lbma_gold_am  69026.3750   75929.01250
4        lbma_gold_pm  68812.6506   75693.91566
5         lbma_silver    993.6946    1093.06406
6    lbma_platinum_am  27761.0648   30537.17128
7    lbma_platinum_pm  27874.1159   30661.52749
8   lbma_palladium_am  18993.4138   20892.75518
9   lbma_palladium_pm  18992.5886   20891.84746
10           mcx_gold  80097.3196   88107.05156
11        mcx_gold_am  79297.1570   87226.87270
12        mcx_gold_pm  79388.3438   87327.17818
13         mcx_silver   1182.8019    1301.08209
14      mcx_silver_am   1182.6237    1300.88607
15      mcx_silver_pm   1183.5248    1301.87728
16          ibja_gold  79649.6223   87614.58453
17        ibja_silver   1181.8315    1300.01465
18             copper      7.6576       8.42336
19           aluminum      1.5501       1.70511
20               lead      0.9715       1.06865
21             nickel      7.9619       8.75809
22               zinc      1.8951       2.08461
23         lme_copper      7.5241       8.27651
24       lme_aluminum      1.5708       1.72788
25           lme_lead      0.9676       1.06436
26         lme_nickel      8.0695       8.87645
27           lme_zinc      1.9301       2.12311

In [ ]:
df.head()

          Metal       Price
0          gold  68698.4984
1        silver    939.8753
2      platinum  27133.9058
3     palladium  18329.6583
4  lbma_gold_am  68958.5420

In [ ]:
df_duplicates = df.duplicated()
df_duplicates[df_duplicates == True]

Series([], dtype: bool)

In [ ]:
df[~df.duplicated()]

                Metal       Price
0                gold  68698.4984
1              silver    939.8753
2            platinum  27133.9058
3           palladium  18329.6583
4        lbma_gold_am  68958.5420
5        lbma_gold_pm  69078.9172
6         lbma_silver    951.5418
7    lbma_platinum_am  26954.9919
8    lbma_platinum_pm  27041.5632
9   lbma_palladium_am  18682.0776
10  lbma_palladium_pm  18609.5226
11           mcx_gold  79792.3298
12        mcx_gold_am  78827.2779
13        mcx_gold_pm  78700.5112
14         mcx_silver   1139.2184
15      mcx_silver_am   1138.6198
16      mcx_silver_pm   1136.3986
17          ibja_gold  78989.7862
18        ibja_silver   1137.7953
19             copper      7.4884
20           aluminum      1.5347
21               lead      0.9620
22             nickel      7.8716
23               zinc      1.8865
24         lme_copper      7.4292
25       lme_aluminum      1.5448
26           lme_lead      0.9699
27         lme_nickel      7.8754
28           lme_zinc      1.8972

In [ ]:
df.duplicated()[df.duplicated() == True]

Series([], dtype: bool)

In [ ]:
#Select *
#df

#Select Count(*) from df
len(df) #Counts the rows of the df.
df.shape[0] #also counts rows

df.shape #counts rows and columns
df.shape[1] #Counts columns

2

In [ ]:

#SELECT Metal_Name
#FROM df;

df["Metal"]


#SELECT Metal_Name, Price_ZAR
#ROM df;

df[["Metal", "Price"]]

                Metal       Price
0                gold  68698.4984
1              silver    939.8753
2            platinum  27133.9058
3           palladium  18329.6583
4        lbma_gold_am  68958.5420
5        lbma_gold_pm  69078.9172
6         lbma_silver    951.5418
7    lbma_platinum_am  26954.9919
8    lbma_platinum_pm  27041.5632
9   lbma_palladium_am  18682.0776
10  lbma_palladium_pm  18609.5226
11           mcx_gold  79792.3298
12        mcx_gold_am  78827.2779
13        mcx_gold_pm  78700.5112
14         mcx_silver   1139.2184
15      mcx_silver_am   1138.6198
16      mcx_silver_pm   1136.3986
17          ibja_gold  78989.7862
18        ibja_silver   1137.7953
19             copper      7.4884
20           aluminum      1.5347
21               lead      0.9620
22             nickel      7.8716
23               zinc      1.8865
24         lme_copper      7.4292
25       lme_aluminum      1.5448
26           lme_lead      0.9699
27         lme_nickel      7.8754
28           lme_zinc      1.8972

In [ ]:
#SELECT *
#FROM df
#WHERE Metal_Name = 'gold';

df[df["Metal"] == "gold"]

  Metal       Price
0  gold  68698.4984

In [ ]:
#SELECT *
#FROM df
#WHERE Price_ZAR > 1000;

df[df["Price"] > 50000]

           Metal       Price
0           gold  68698.4984
4   lbma_gold_am  68958.5420
5   lbma_gold_pm  69078.9172
11      mcx_gold  79792.3298
12   mcx_gold_am  78827.2779
13   mcx_gold_pm  78700.5112
17     ibja_gold  78989.7862

In [ ]:
#SELECT Metal_Name, Price_ZAR
#FROM df
#WHERE Price_ZAR > 5000;

df[df["Price"] > 50000][["Metal", "Price"]]

#df[df["Price"] > 5000] = WHERE Price > 5000
#[["Metal", "Price"]] = SELECT Metal, Price

#df[WHERE CONDITION][SELECT COLUMNS]

           Metal       Price
0           gold  68698.4984
4   lbma_gold_am  68958.5420
5   lbma_gold_pm  69078.9172
11      mcx_gold  79792.3298
12   mcx_gold_am  78827.2779
13   mcx_gold_pm  78700.5112
17     ibja_gold  78989.7862

In [ ]:
#SELECT Metal, Price
#FROM df
#WHERE Price < 2000;

df[df["Price"] < 2000 ][["Metal", "Price"]]

            Metal      Price
1          silver   949.5298
6     lbma_silver   949.7273
14     mcx_silver  1138.3034
15  mcx_silver_am  1135.4841
16  mcx_silver_pm  1135.4841
18    ibja_silver  1136.8535
19         copper     7.5413
20       aluminum     1.5341
21           lead     0.9628
22         nickel     7.8566
23           zinc     1.8888
24     lme_copper     7.4150
25   lme_aluminum     1.5419
26       lme_lead     0.9680
27     lme_nickel     7.8604
28       lme_zinc     1.8936

In [ ]:
#SELECT Metal, Price
#FROM df
#WHERE Price > 2000
#AND Price < 10000;

#df[(df["Price"] > 2000) & (df["Price"] < 10000)][["Metal", "Price"]]

df

                Metal       Price
0                gold  68825.3987
1              silver    949.5298
2            platinum  27255.3220
3           palladium  18636.1661
4        lbma_gold_am  68827.0445
5        lbma_gold_pm  68947.1903
6         lbma_silver    949.7273
7    lbma_platinum_am  26903.5913
8    lbma_platinum_pm  26989.9975
9   lbma_palladium_am  18646.4526
10  lbma_palladium_pm  18574.0360
11           mcx_gold  79728.1546
12        mcx_gold_am  78637.2116
13        mcx_gold_pm  78637.2116
14         mcx_silver   1138.3034
15      mcx_silver_am   1135.4841
16      mcx_silver_pm   1135.4841
17          ibja_gold  78926.2362
18        ibja_silver   1136.8535
19             copper      7.5413
20           aluminum      1.5341
21               lead      0.9628
22             nickel      7.8566
23               zinc      1.8888
24         lme_copper      7.4150
25       lme_aluminum      1.5419
26           lme_lead      0.9680
27         lme_nickel      7.8604
28           lme_zinc      1.8936

In [ ]:
df[(df["Price"] > 10000) & (df["Price"] < 30000)][["Metal","Price"]]

                Metal       Price
2            platinum  27255.3220
3           palladium  18636.1661
7    lbma_platinum_am  26903.5913
8    lbma_platinum_pm  26989.9975
9   lbma_palladium_am  18646.4526
10  lbma_palladium_pm  18574.0360

In [ ]:
# SELECT Metal, Price
# FROM df
# WHERE Metal = 'gold'
#    OR Metal = 'silver';

df[(df["Metal"] == "gold") | (df["Metal"] == "silver")][["Metal","Price"]]

    Metal       Price
0    gold  68825.3987
1  silver    949.5298

In [ ]:
# SELECT Metal, Price
# FROM df
# WHERE Price > 10000
# AND (Metal = 'gold' OR Metal = 'platinum');

df[(df["Price"] > 10000) & ((df["Metal"] == "gold") | (df["Metal"] == "platinum"))][["Metal","Price"]]

      Metal       Price
0      gold  68825.3987
2  platinum  27255.3220

In [ ]:
# SELECT Metal, Price
# FROM df
# WHERE Metal IN ('gold', 'silver', 'palladium');

df[df["Metal"].isin(["gold","silver","platinum"])][["Metal", "Price"]]

      Metal       Price
0      gold  67701.4940
1    silver    943.7666
2  platinum  26710.3375

In [ ]:
# SELECT *
# FROM df
# WHERE Metal NOT IN ('platinum', 'palladium');

df[~df["Metal"].isin(["platinum","palladium"])][["Metal","Price"]]

                Metal       Price
0                gold  67701.4940
1              silver    943.7666
4        lbma_gold_am  67447.5382
5        lbma_gold_pm  67515.4234
6         lbma_silver    941.3129
7    lbma_platinum_am  26742.6442
8    lbma_platinum_pm  26903.7692
9   lbma_palladium_am  17825.1579
10  lbma_palladium_pm  18514.6416
11           mcx_gold  78721.4116
12        mcx_gold_am  77351.5343
13        mcx_gold_pm  77303.0365
14         mcx_silver   1127.1987
15      mcx_silver_am   1109.9755
16      mcx_silver_pm   1112.8578
17          ibja_gold  77660.4328
18        ibja_silver   1114.3447
19             copper      7.4589
20           aluminum      1.5329
21               lead      0.9639
22             nickel      8.2736
23               zinc      1.8991
24         lme_copper      7.3046
25       lme_aluminum      1.5248
26           lme_lead      0.9636
27         lme_nickel      7.9218
28           lme_zinc      1.8800

In [ ]:
# SELECT *
# FROM df
# WHERE Metal NOT LIKE '%silver%';

df[~df["Metal"].str.contains("silver")][["Metal","Price"]]

                Metal       Price
0                gold  67701.4940
2            platinum  26710.3375
3           palladium  17874.2642
4        lbma_gold_am  67447.5382
5        lbma_gold_pm  67515.4234
7    lbma_platinum_am  26742.6442
8    lbma_platinum_pm  26903.7692
9   lbma_palladium_am  17825.1579
10  lbma_palladium_pm  18514.6416
11           mcx_gold  78721.4116
12        mcx_gold_am  77351.5343
13        mcx_gold_pm  77303.0365
17          ibja_gold  77660.4328
19             copper      7.4589
20           aluminum      1.5329
21               lead      0.9639
22             nickel      8.2736
23               zinc      1.8991
24         lme_copper      7.3046
25       lme_aluminum      1.5248
26           lme_lead      0.9636
27         lme_nickel      7.9218
28           lme_zinc      1.8800

In [ ]:
# SELECT *
# FROM df
# WHERE Metal LIKE 'lbma%';


df[df["Metal"].str.contains("lbma")][["Metal", "Price"]]

                Metal       Price
4        lbma_gold_am  67447.5382
5        lbma_gold_pm  67515.4234
6         lbma_silver    941.3129
7    lbma_platinum_am  26742.6442
8    lbma_platinum_pm  26903.7692
9   lbma_palladium_am  17825.1579
10  lbma_palladium_pm  18514.6416

In [ ]:
# SELECT *
# FROM df
# WHERE Metal LIKE 'mcx%';

df[df["Metal"].str.startswith("mcx")][["Metal", "Price"]]

            Metal       Price
11       mcx_gold  78721.4116
12    mcx_gold_am  77351.5343
13    mcx_gold_pm  77303.0365
14     mcx_silver   1127.1987
15  mcx_silver_am   1109.9755
16  mcx_silver_pm   1112.8578

In [ ]:
df[df["Metal"].str.endswith("pm")][["Metal", "Price"]]

                Metal       Price
5        lbma_gold_pm  67515.4234
8    lbma_platinum_pm  26903.7692
10  lbma_palladium_pm  18514.6416
13        mcx_gold_pm  77303.0365
16      mcx_silver_pm   1112.8578

In [ ]:
# SELECT *
# FROM df
# WHERE Metal LIKE 'lbma%'
# AND Metal LIKE '%pm';

df[(df["Metal"].str.startswith("lbma")) & (df["Metal"].str.endswith("pm"))][["Metal", "Price"]]

                Metal       Price
5        lbma_gold_pm  67515.4234
8    lbma_platinum_pm  26903.7692
10  lbma_palladium_pm  18514.6416

In [ ]:
# SELECT *
# FROM df
# WHERE Metal LIKE 'mcx%'
# OR Metal LIKE '%silver%';

df[(df["Metal"].str.startswith("mcx")) | (df["Metal"].str.contains("silver"))][["Metal", "Price"]]

            Metal       Price
1          silver    943.7666
6     lbma_silver    941.3129
11       mcx_gold  78721.4116
12    mcx_gold_am  77351.5343
13    mcx_gold_pm  77303.0365
14     mcx_silver   1127.1987
15  mcx_silver_am   1109.9755
16  mcx_silver_pm   1112.8578
18    ibja_silver   1114.3447

In [ ]:
# SELECT *
# FROM df
# WHERE (Metal LIKE 'lbma%' OR Metal LIKE 'mcx%')
# AND Metal NOT LIKE '%silver%';

df[((df["Metal"].str.startswith("lbma")) | (df["Metal"].str.startswith("mcx"))) & (~df["Metal"].str.contains("silver"))][["Metal", "Price"]]

                Metal       Price
4        lbma_gold_am  67447.5382
5        lbma_gold_pm  67515.4234
7    lbma_platinum_am  26742.6442
8    lbma_platinum_pm  26903.7692
9   lbma_palladium_am  17825.1579
10  lbma_palladium_pm  18514.6416
11           mcx_gold  78721.4116
12        mcx_gold_am  77351.5343
13        mcx_gold_pm  77303.0365

In [ ]:
# SELECT *
# FROM df
# WHERE Price BETWEEN 1000 AND 20000;

df[df["Price"].between(1000, 20000)]

                Metal       Price
3           palladium  17874.2642
9   lbma_palladium_am  17825.1579
10  lbma_palladium_pm  18514.6416
14         mcx_silver   1127.1987
15      mcx_silver_am   1109.9755
16      mcx_silver_pm   1112.8578
18        ibja_silver   1114.3447

In [ ]:
# SELECT *
# FROM df
# WHERE Price NOT BETWEEN 2000 AND 30000;

df[~df["Price"].between(2000, 30000)]

            Metal       Price
0            gold  67701.4940
1          silver    943.7666
4    lbma_gold_am  67447.5382
5    lbma_gold_pm  67515.4234
6     lbma_silver    941.3129
11       mcx_gold  78721.4116
12    mcx_gold_am  77351.5343
13    mcx_gold_pm  77303.0365
14     mcx_silver   1127.1987
15  mcx_silver_am   1109.9755
16  mcx_silver_pm   1112.8578
17      ibja_gold  77660.4328
18    ibja_silver   1114.3447
19         copper      7.4589
20       aluminum      1.5329
21           lead      0.9639
22         nickel      8.2736
23           zinc      1.8991
24     lme_copper      7.3046
25   lme_aluminum      1.5248
26       lme_lead      0.9636
27     lme_nickel      7.9218
28       lme_zinc      1.8800

In [ ]:
# SELECT *
# FROM df
# WHERE Price IS NULL;

df[~df["Price"].isna()]

                Metal       Price
0                gold  67701.4940
1              silver    943.7666
2            platinum  26710.3375
3           palladium  17874.2642
4        lbma_gold_am  67447.5382
5        lbma_gold_pm  67515.4234
6         lbma_silver    941.3129
7    lbma_platinum_am  26742.6442
8    lbma_platinum_pm  26903.7692
9   lbma_palladium_am  17825.1579
10  lbma_palladium_pm  18514.6416
11           mcx_gold  78721.4116
12        mcx_gold_am  77351.5343
13        mcx_gold_pm  77303.0365
14         mcx_silver   1127.1987
15      mcx_silver_am   1109.9755
16      mcx_silver_pm   1112.8578
17          ibja_gold  77660.4328
18        ibja_silver   1114.3447
19             copper      7.4589
20           aluminum      1.5329
21               lead      0.9639
22             nickel      8.2736
23               zinc      1.8991
24         lme_copper      7.3046
25       lme_aluminum      1.5248
26           lme_lead      0.9636
27         lme_nickel      7.9218
28           lme_zinc      1.8800

In [5]:
df.loc[0, "Price"] = None

In [ ]:
df

                Metal       Price
0                gold         NaN
1              silver    943.7666
2            platinum  26710.3375
3           palladium  17874.2642
4        lbma_gold_am  67447.5382
5        lbma_gold_pm  67515.4234
6         lbma_silver    941.3129
7    lbma_platinum_am  26742.6442
8    lbma_platinum_pm  26903.7692
9   lbma_palladium_am  17825.1579
10  lbma_palladium_pm  18514.6416
11           mcx_gold  78721.4116
12        mcx_gold_am  77351.5343
13        mcx_gold_pm  77303.0365
14         mcx_silver   1127.1987
15      mcx_silver_am   1109.9755
16      mcx_silver_pm   1112.8578
17          ibja_gold  77660.4328
18        ibja_silver   1114.3447
19             copper      7.4589
20           aluminum      1.5329
21               lead      0.9639
22             nickel      8.2736
23               zinc      1.8991
24         lme_copper      7.3046
25       lme_aluminum      1.5248
26           lme_lead      0.9636
27         lme_nickel      7.9218
28           lme_zinc      1.8800

In [7]:
# SELECT *
# FROM df
# WHERE Price IS NULL;

df[df["Price"].isna()]

  Metal  Price
0  gold    NaN

In [6]:
# SELECT *
# FROM df
# WHERE Price IS NOT NULL;

df[~df["Price"].isna()]

                Metal       Price
1              silver    894.3596
2            platinum  25718.7673
3           palladium  17285.7485
4        lbma_gold_am  66792.4928
5        lbma_gold_pm  66570.2216
6         lbma_silver    894.0610
7    lbma_platinum_am  25875.5182
8    lbma_platinum_pm  25853.1252
9   lbma_palladium_am  17567.7178
10  lbma_palladium_pm  17498.8801
11           mcx_gold  77182.1217
12        mcx_gold_am  76606.0695
13        mcx_gold_pm  76642.4788
14         mcx_silver   1063.6240
15      mcx_silver_am   1056.3637
16      mcx_silver_pm   1055.2059
17          ibja_gold  76968.1011
18        ibja_silver   1056.5147
19             copper      7.4691
20           aluminum      1.5613
21               lead      0.9775
22             nickel      8.1596
23               zinc      1.9317
24         lme_copper      7.3623
25       lme_aluminum      1.5571
26           lme_lead      0.9844
27         lme_nickel      8.2032
28           lme_zinc      1.9223

In [12]:
# SELECT *
# FROM df
# WHERE Price IS NOT NULL
# AND Price > 20000;

df[(~df["Price"].isna()) & (df["Price"] > 20000)]

               Metal       Price
2           platinum  25718.7673
4       lbma_gold_am  66792.4928
5       lbma_gold_pm  66570.2216
7   lbma_platinum_am  25875.5182
8   lbma_platinum_pm  25853.1252
11          mcx_gold  77182.1217
12       mcx_gold_am  76606.0695
13       mcx_gold_pm  76642.4788
17         ibja_gold  76968.1011

In [17]:
# SELECT *
# FROM df
# ORDER BY Price DESC;

#df.sort_values("Price")
df.sort_values("Price", ascending=False)

                Metal       Price
11           mcx_gold  77182.1217
17          ibja_gold  76968.1011
13        mcx_gold_pm  76642.4788
12        mcx_gold_am  76606.0695
4        lbma_gold_am  66792.4928
5        lbma_gold_pm  66570.2216
7    lbma_platinum_am  25875.5182
8    lbma_platinum_pm  25853.1252
2            platinum  25718.7673
9   lbma_palladium_am  17567.7178
10  lbma_palladium_pm  17498.8801
3           palladium  17285.7485
14         mcx_silver   1063.6240
18        ibja_silver   1056.5147
15      mcx_silver_am   1056.3637
16      mcx_silver_pm   1055.2059
1              silver    894.3596
6         lbma_silver    894.0610
27         lme_nickel      8.2032
22             nickel      8.1596
19             copper      7.4691
24         lme_copper      7.3623
23               zinc      1.9317
28           lme_zinc      1.9223
20           aluminum      1.5613
25       lme_aluminum      1.5571
26           lme_lead      0.9844
21               lead      0.9775
0                gold         NaN

In [19]:
# SELECT *
# FROM df
# ORDER BY Metal ASC, Price DESC;

df.sort_values(["Metal", "Price"], ascending=[True, False])

                Metal       Price
20           aluminum      1.5613
19             copper      7.4691
0                gold         NaN
17          ibja_gold  76968.1011
18        ibja_silver   1056.5147
4        lbma_gold_am  66792.4928
5        lbma_gold_pm  66570.2216
9   lbma_palladium_am  17567.7178
10  lbma_palladium_pm  17498.8801
7    lbma_platinum_am  25875.5182
8    lbma_platinum_pm  25853.1252
6         lbma_silver    894.0610
21               lead      0.9775
25       lme_aluminum      1.5571
24         lme_copper      7.3623
26           lme_lead      0.9844
27         lme_nickel      8.2032
28           lme_zinc      1.9223
11           mcx_gold  77182.1217
12        mcx_gold_am  76606.0695
13        mcx_gold_pm  76642.4788
14         mcx_silver   1063.6240
15      mcx_silver_am   1056.3637
16      mcx_silver_pm   1055.2059
22             nickel      8.1596
3           palladium  17285.7485
2            platinum  25718.7673
1              silver    894.3596
23               zinc      1.9317

In [21]:
# SELECT *
# FROM df
# ORDER BY Price DESC, Metal ASC;

df.sort_values(["Price", "Metal"], ascending=[False, True])

                Metal       Price
11           mcx_gold  77182.1217
17          ibja_gold  76968.1011
13        mcx_gold_pm  76642.4788
12        mcx_gold_am  76606.0695
4        lbma_gold_am  66792.4928
5        lbma_gold_pm  66570.2216
7    lbma_platinum_am  25875.5182
8    lbma_platinum_pm  25853.1252
2            platinum  25718.7673
9   lbma_palladium_am  17567.7178
10  lbma_palladium_pm  17498.8801
3           palladium  17285.7485
14         mcx_silver   1063.6240
18        ibja_silver   1056.5147
15      mcx_silver_am   1056.3637
16      mcx_silver_pm   1055.2059
1              silver    894.3596
6         lbma_silver    894.0610
27         lme_nickel      8.2032
22             nickel      8.1596
19             copper      7.4691
24         lme_copper      7.3623
23               zinc      1.9317
28           lme_zinc      1.9223
20           aluminum      1.5613
25       lme_aluminum      1.5571
26           lme_lead      0.9844
21               lead      0.9775
0                gold         NaN

In [28]:
# SELECT Metal, Price
# FROM df
# WHERE Price < 20000
# ORDER BY Price DESC;

df[df["Price"] < 20000].sort_values("Price", ascending=False)

                Metal       Price
9   lbma_palladium_am  17567.7178
10  lbma_palladium_pm  17498.8801
3           palladium  17285.7485
14         mcx_silver   1063.6240
18        ibja_silver   1056.5147
15      mcx_silver_am   1056.3637
16      mcx_silver_pm   1055.2059
1              silver    894.3596
6         lbma_silver    894.0610
27         lme_nickel      8.2032
22             nickel      8.1596
19             copper      7.4691
24         lme_copper      7.3623
23               zinc      1.9317
28           lme_zinc      1.9223
20           aluminum      1.5613
25       lme_aluminum      1.5571
26           lme_lead      0.9844
21               lead      0.9775

In [31]:
# SELECT Metal, Price
# FROM df
# WHERE Price > 1000
# AND Price < 30000
# ORDER BY Metal ASC, Price DESC;

df[(df["Price"] > 1000) & (df["Price"] < 30000)].sort_values(["Metal", "Price"], ascending=[True, False])
#df[df["Price"].between(1000, 30000)].sort_values(["Metal", "Price"], ascending=[True, False])

                Metal       Price
18        ibja_silver   1056.5147
9   lbma_palladium_am  17567.7178
10  lbma_palladium_pm  17498.8801
7    lbma_platinum_am  25875.5182
8    lbma_platinum_pm  25853.1252
14         mcx_silver   1063.6240
15      mcx_silver_am   1056.3637
16      mcx_silver_pm   1055.2059
3           palladium  17285.7485
2            platinum  25718.7673

In [32]:
# SELECT Metal, Price
# FROM df
# WHERE Price > 1000
# AND Price < 30000
# ORDER BY Metal ASC, Price DESC;

#df[(df["Price"] > 1000) & (df["Price"] < 30000)].sort_values(["Metal", "Price"], ascending=[True, False])
df[df["Price"].between(1000, 30000)].sort_values(["Metal", "Price"], ascending=[True, False])

                Metal       Price
18        ibja_silver   1056.5147
9   lbma_palladium_am  17567.7178
10  lbma_palladium_pm  17498.8801
7    lbma_platinum_am  25875.5182
8    lbma_platinum_pm  25853.1252
14         mcx_silver   1063.6240
15      mcx_silver_am   1056.3637
16      mcx_silver_pm   1055.2059
3           palladium  17285.7485
2            platinum  25718.7673

In [39]:
# SELECT COUNT(*)
# FROM df
# WHERE Price > 20000;

print(len(df))
print(df.describe())
print(df.shape)

29
              Price
count     28.000000
mean   20593.625000
std    29540.256898
min        0.977500
25%        7.442400
50%     1056.439200
75%    25858.723450
max    77182.121700
(29, 2)

In [43]:
# SELECT COUNT(*)
# FROM df
# WHERE Price > 20000;

print(df[df["Price"] > 20000])
print(len(df[df["Price"] > 20000]))

               Metal       Price
2           platinum  25718.7673
4       lbma_gold_am  66792.4928
5       lbma_gold_pm  66570.2216
7   lbma_platinum_am  25875.5182
8   lbma_platinum_pm  25853.1252
11          mcx_gold  77182.1217
12       mcx_gold_am  76606.0695
13       mcx_gold_pm  76642.4788
17         ibja_gold  76968.1011
9

In [45]:
# SELECT SUM(Price)
# FROM df;

df["Price"].sum()

np.float64(576621.4999999999)

In [54]:
# SELECT SUM(Price)
# FROM df
# WHERE Price > 20000;

df[df["Price"] > 20000]["Price"].sum()

np.float64(518208.89619999996)

In [53]:


df[(df["Price"] > 0) & (df["Metal"].isin(["gold", "silver", "platinum"]))].sum()

Metal    silverplatinum
Price        26613.1269
dtype: object