<a href="https://colab.research.google.com/github/Otto-C/Otto-C.github.io/blob/main/01_Bullion_API_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import userdata

api_key = userdata.get('METALS_API_KEY')

print("API key loaded successfully!" if api_key else "API key not found")

API key loaded successfully!

In [2]:
import requests
url = 'https://api.metals.dev/v1/latest'

params = {
    "api_key": api_key,
    "currency": "ZAR",
    "unit": "toz"
}

response = requests.get(url, params=params, timeout=30)

print("HTTP Status", response.status_code)
print("API Status", response.json().get("status"))

HTTP Status 200
API Status success

In [3]:
data = response.json()
print(data)

{'status': 'success', 'currency': 'ZAR', 'unit': 'toz', 'metals': {'gold': 68878.0415, 'silver': 987.3737, 'platinum': 27740.1734, 'palladium': 18651.7187, 'lbma_gold_am': 69015.9927, 'lbma_gold_pm': 68841.9036, 'lbma_silver': 993.5452, 'lbma_platinum_am': 27756.8892, 'lbma_platinum_pm': 27869.9233, 'lbma_palladium_am': 18990.557, 'lbma_palladium_pm': 18989.7319, 'mcx_gold': 80488.6339, 'mcx_gold_am': 79341.435, 'mcx_gold_pm': 79432.6708, 'mcx_silver': 1193.5198, 'mcx_silver_am': 1183.2841, 'mcx_silver_pm': 1184.185, 'ibja_gold': 79694.0998, 'ibja_silver': 1182.4755, 'copper': 7.6879, 'aluminum': 1.5575, 'lead': 0.9734, 'nickel': 8.0013, 'zinc': 1.9269, 'lme_copper': 7.5229, 'lme_aluminum': 1.5705, 'lme_lead': 0.9675, 'lme_nickel': 8.0683, 'lme_zinc': 1.9298}, 'currencies': {'AED': 4.49321476, 'AFN': 0.25427088, 'ALL': 0.20206199, 'AMD': 0.04561749, 'ANG': 9.18271045, 'AOA': 0.01804642, 'ARS': 0.01085859, 'AUD': 11.51755278, 'AWG': 9.21862078, 'AZN': 9.70663466, 'BAM': 9.4440902, 'BBD': 8.2506656, 'BDT': 0.13391593, 'BGN': 9.4440902, 'BHD': 43.88651913, 'BIF': 0.0055001, 'BMD': 16.50133119, 'BND': 12.89153028, 'BOB': 1.40853764, 'BRL': 3.29076249, 'BSD': 16.50133119, 'BTC': 1374526.75893911, 'BTN': 0.17356865, 'BWP': 1.20169401, 'BYN': 5.50044373, 'BYR': 0.00060331, 'BZD': 8.18011652, 'CAD': 11.59911662, 'CDF': 0.00714324, 'CHF': 19.81899054, 'CLP': 0.01681488, 'CNH': 2.46572066, 'CNY': 2.46554633, 'COP': 0.00516243, 'CRC': 0.03625127, 'CUC': 16.50133119, 'CUP': 0.68755547, 'CVE': 0.16750734, 'CZK': 0.75812216, 'DJF': 0.09265591, 'DKK': 2.47086255, 'DOP': 0.26931562, 'DZD': 0.12268125, 'EEK': 1.18051127, 'EGP': 0.31281202, 'ERN': 1.10008875, 'ETB': 0.10194205, 'EUR': 18.47103494, 'FJD': 7.32824118, 'FKP': 21.85599509, 'GBP': 21.85599509, 'GEL': 6.36571646, 'GGP': 21.85599509, 'GHS': 1.4112311, 'GIP': 21.85599509, 'GMD': 0.22130927, 'GNF': 0.00187404, 'GTQ': 2.15853431, 'GYD': 0.07896246, 'HKD': 2.10271358, 'HNL': 0.61455645, 'HRK': 2.45152763, 'HTG': 0.12432527, 'HUF': 0.05071126, 'IDR': 0.00092216, 'ILS': 5.37715531, 'IMP': 21.85599509, 'INR': 0.17356865, 'IQD': 0.01091, 'IRR': 9.17e-06, 'ISK': 0.13560867, 'JEP': 21.85599509, 'JMD': 0.10419694, 'JOD': 23.27409195, 'JPY': 0.10419574, 'KES': 0.1272265, 'KGS': 0.18863602, 'KHR': 0.00405639, 'KMF': 0.03754521, 'KPW': 0.018332, 'KRW': 0.01229801, 'KWD': 53.0310342, 'KYD': 19.86809631, 'KZT': 0.03669489, 'LAK': 0.00073855, 'LBP': 0.00018318, 'LKR': 0.049863, 'LRD': 0.0966139, 'LSL': 1, 'LTL': 5.34958148, 'LVL': 26.28206452, 'LYD': 2.56612779, 'MAD': 1.68502106, 'MDL': 0.92275337, 'MGA': 0.00367976, 'MKD': 0.30014416, 'MMK': 0.00785727, 'MNT': 0.00458607, 'MOP': 2.0414695, 'MRU': 0.41218017, 'MUR': 0.34602987, 'MVR': 1.06735674, 'MWK': 0.009519, 'MXN': 0.89961006, 'MYR': 4.03753695, 'MZN': 0.25829426, 'NAD': 1, 'NGN': 0.01241194, 'NIO': 0.4484528, 'NOK': 1.73235162, 'NPR': 0.10842958, 'NTD': 0.55643479, 'NZD': 9.26199034, 'OMR': 42.85443282, 'PAB': 16.50133119, 'PEN': 4.79306949, 'PGK': 3.77387173, 'PHP': 0.26284298, 'PKR': 0.0596153, 'PLN': 4.22256248, 'PYG': 0.00288735, 'QAR': 4.53333275, 'RON': 3.46237613, 'RSD': 0.15733541, 'RUB': 0.19728995, 'RWF': 0.01118868, 'SAR': 4.40035499, 'SBD': 2.05507657, 'SCR': 1.1025535, 'SDG': 0.02749529, 'SEK': 1.65453166, 'SGD': 12.89153028, 'SHP': 21.85599509, 'SKK': 0.61312604, 'SLE': 0.71903553, 'SLL': 0.00072689, 'SOS': 0.02884865, 'SPL': 99.00798756, 'SRD': 0.43828258, 'STN': 0.74666546, 'SVC': 1.88586642, 'SYP': 0.13579107, 'SZL': 1, 'THB': 0.4912792, 'TJS': 1.78671252, 'TMT': 4.7146562, 'TND': 5.49398632, 'TOP': 6.8729384, 'TRY': 0.3342976, 'TTD': 2.42688437, 'TVD': 11.51755278, 'TWD': 0.51308476, 'TZS': 0.00627569, 'UAH': 0.36587553, 'UGX': 0.00399193, 'USD': 16.50133119, 'UYU': 0.41017471, 'UZS': 0.0013852, 'VED': 0.01886763, 'VEF': 4.57e-06, 'VES': 0.01886763, 'VND': 0.00063674, 'VUV': 0.13843984, 'WST': 5.91756732, 'XAF': 0.02815891, 'XCD': 6.09036306, 'XDR': 22.58765683, 'XOF': 0.02815891, 'XPF': 0.15478727, 'YER': 0.06989663, 'ZAR': 1, 'ZMW': 0.82518879, 'ZWD': 0.04559631, 'ZWL': 0.00024774}, 'timestamps': {'metal': '2026-10-13T13:52:05.528Z', 'currency': '2026-10-13T13:51:10.327Z'}}

In [4]:
import json

print(json.dumps(data, indent=4))

{
    "status": "success",
    "currency": "ZAR",
    "unit": "toz",
    "metals": {
        "gold": 68878.0415,
        "silver": 987.3737,
        "platinum": 27740.1734,
        "palladium": 18651.7187,
        "lbma_gold_am": 69015.9927,
        "lbma_gold_pm": 68841.9036,
        "lbma_silver": 993.5452,
        "lbma_platinum_am": 27756.8892,
        "lbma_platinum_pm": 27869.9233,
        "lbma_palladium_am": 18990.557,
        "lbma_palladium_pm": 18989.7319,
        "mcx_gold": 80488.6339,
        "mcx_gold_am": 79341.435,
        "mcx_gold_pm": 79432.6708,
        "mcx_silver": 1193.5198,
        "mcx_silver_am": 1183.2841,
        "mcx_silver_pm": 1184.185,
        "ibja_gold": 79694.0998,
        "ibja_silver": 1182.4755,
        "copper": 7.6879,
        "aluminum": 1.5575,
        "lead": 0.9734,
        "nickel": 8.0013,
        "zinc": 1.9269,
        "lme_copper": 7.5229,
        "lme_aluminum": 1.5705,
        "lme_lead": 0.9675,
        "lme_nickel": 8.0683,
        "lme_zinc": 1.9298
    },
    "currencies": {
        "AED": 4.49321476,
        "AFN": 0.25427088,
        "ALL": 0.20206199,
        "AMD": 0.04561749,
        "ANG": 9.18271045,
        "AOA": 0.01804642,
        "ARS": 0.01085859,
        "AUD": 11.51755278,
        "AWG": 9.21862078,
        "AZN": 9.70663466,
        "BAM": 9.4440902,
        "BBD": 8.2506656,
        "BDT": 0.13391593,
        "BGN": 9.4440902,
        "BHD": 43.88651913,
        "BIF": 0.0055001,
        "BMD": 16.50133119,
        "BND": 12.89153028,
        "BOB": 1.40853764,
        "BRL": 3.29076249,
        "BSD": 16.50133119,
        "BTC": 1374526.75893911,
        "BTN": 0.17356865,
        "BWP": 1.20169401,
        "BYN": 5.50044373,
        "BYR": 0.00060331,
        "BZD": 8.18011652,
        "CAD": 11.59911662,
        "CDF": 0.00714324,
        "CHF": 19.81899054,
        "CLP": 0.01681488,
        "CNH": 2.46572066,
        "CNY": 2.46554633,
        "COP": 0.00516243,
        "CRC": 0.03625127,
        "CUC": 16.50133119,
        "CUP": 0.68755547,
        "CVE": 0.16750734,
        "CZK": 0.75812216,
        "DJF": 0.09265591,
        "DKK": 2.47086255,
        "DOP": 0.26931562,
        "DZD": 0.12268125,
        "EEK": 1.18051127,
        "EGP": 0.31281202,
        "ERN": 1.10008875,
        "ETB": 0.10194205,
        "EUR": 18.47103494,
        "FJD": 7.32824118,
        "FKP": 21.85599509,
        "GBP": 21.85599509,
        "GEL": 6.36571646,
        "GGP": 21.85599509,
        "GHS": 1.4112311,
        "GIP": 21.85599509,
        "GMD": 0.22130927,
        "GNF": 0.00187404,
        "GTQ": 2.15853431,
        "GYD": 0.07896246,
        "HKD": 2.10271358,
        "HNL": 0.61455645,
        "HRK": 2.45152763,
        "HTG": 0.12432527,
        "HUF": 0.05071126,
        "IDR": 0.00092216,
        "ILS": 5.37715531,
        "IMP": 21.85599509,
        "INR": 0.17356865,
        "IQD": 0.01091,
        "IRR": 9.17e-06,
        "ISK": 0.13560867,
        "JEP": 21.85599509,
        "JMD": 0.10419694,
        "JOD": 23.27409195,
        "JPY": 0.10419574,
        "KES": 0.1272265,
        "KGS": 0.18863602,
        "KHR": 0.00405639,
        "KMF": 0.03754521,
        "KPW": 0.018332,
        "KRW": 0.01229801,
        "KWD": 53.0310342,
        "KYD": 19.86809631,
        "KZT": 0.03669489,
        "LAK": 0.00073855,
        "LBP": 0.00018318,
        "LKR": 0.049863,
        "LRD": 0.0966139,
        "LSL": 1,
        "LTL": 5.34958148,
        "LVL": 26.28206452,
        "LYD": 2.56612779,
        "MAD": 1.68502106,
        "MDL": 0.92275337,
        "MGA": 0.00367976,
        "MKD": 0.30014416,
        "MMK": 0.00785727,
        "MNT": 0.00458607,
        "MOP": 2.0414695,
        "MRU": 0.41218017,
        "MUR": 0.34602987,
        "MVR": 1.06735674,
        "MWK": 0.009519,
        "MXN": 0.89961006,
        "MYR": 4.03753695,
        "MZN": 0.25829426,
        "NAD": 1,
        "NGN": 0.01241194,
        "NIO": 0.4484528,
        "NOK": 1.73235162,
        "NPR": 0.10842958,
        "NTD": 0.55643479,
        "NZD": 9.26199034,
        "OMR": 42.85443282,
        "PAB": 16.50133119,
        "PEN": 4.79306949,
        "PGK": 3.77387173,
        "PHP": 0.26284298,
        "PKR": 0.0596153,
        "PLN": 4.22256248,
        "PYG": 0.00288735,
        "QAR": 4.53333275,
        "RON": 3.46237613,
        "RSD": 0.15733541,
        "RUB": 0.19728995,
        "RWF": 0.01118868,
        "SAR": 4.40035499,
        "SBD": 2.05507657,
        "SCR": 1.1025535,
        "SDG": 0.02749529,
        "SEK": 1.65453166,
        "SGD": 12.89153028,
        "SHP": 21.85599509,
        "SKK": 0.61312604,
        "SLE": 0.71903553,
        "SLL": 0.00072689,
        "SOS": 0.02884865,
        "SPL": 99.00798756,
        "SRD": 0.43828258,
        "STN": 0.74666546,
        "SVC": 1.88586642,
        "SYP": 0.13579107,
        "SZL": 1,
        "THB": 0.4912792,
        "TJS": 1.78671252,
        "TMT": 4.7146562,
        "TND": 5.49398632,
        "TOP": 6.8729384,
        "TRY": 0.3342976,
        "TTD": 2.42688437,
        "TVD": 11.51755278,
        "TWD": 0.51308476,
        "TZS": 0.00627569,
        "UAH": 0.36587553,
        "UGX": 0.00399193,
        "USD": 16.50133119,
        "UYU": 0.41017471,
        "UZS": 0.0013852,
        "VED": 0.01886763,
        "VEF": 4.57e-06,
        "VES": 0.01886763,
        "VND": 0.00063674,
        "VUV": 0.13843984,
        "WST": 5.91756732,
        "XAF": 0.02815891,
        "XCD": 6.09036306,
        "XDR": 22.58765683,
        "XOF": 0.02815891,
        "XPF": 0.15478727,
        "YER": 0.06989663,
        "ZAR": 1,
        "ZMW": 0.82518879,
        "ZWD": 0.04559631,
        "ZWL": 0.00024774
    },
    "timestamps": {
        "metal": "2026-10-13T13:52:05.528Z",
        "currency": "2026-10-13T13:51:10.327Z"
    }
}

In [5]:
gold_price = data["metals"]["gold"]
silver_price = data["metals"]["silver"]
platinum_price = data["metals"]["platinum"]
palladium_price = data["metals"]["palladium"]
status_code = data["status"]
currency = data["currency"]
zar = data["unit"]

In [6]:
print(gold_price)
print(silver_price)
print(status_code)
print(currency)
print(zar)
print("")
print("Gold Price", round(gold_price,2))
print("Silver Price", round(silver_price, 2))
print("Platinum Price", round(platinum_price, 2))
print("Palladium Price", round(palladium_price, 2))

print("")
print("Status Code", status_code)
print("Currency", currency)
print("ZAR", zar)

68878.0415
987.3737
success
ZAR
toz

Gold Price 68878.04
Silver Price 987.37
Platinum Price 27740.17
Palladium Price 18651.72

Status Code success
Currency ZAR
ZAR toz

In [7]:
for metal in ["gold", "silver", "platinum", "palladium"]:
    price = data["metals"][metal]
    print(metal.title(), "Price", round(price, 2))

Gold Price 68878.04
Silver Price 987.37
Platinum Price 27740.17
Palladium Price 18651.72

In [8]:
from pprint import pprint

pprint(data["metals"])

pprint(data["metals"].items())

{'aluminum': 1.5575,
 'copper': 7.6879,
 'gold': 68878.0415,
 'ibja_gold': 79694.0998,
 'ibja_silver': 1182.4755,
 'lbma_gold_am': 69015.9927,
 'lbma_gold_pm': 68841.9036,
 'lbma_palladium_am': 18990.557,
 'lbma_palladium_pm': 18989.7319,
 'lbma_platinum_am': 27756.8892,
 'lbma_platinum_pm': 27869.9233,
 'lbma_silver': 993.5452,
 'lead': 0.9734,
 'lme_aluminum': 1.5705,
 'lme_copper': 7.5229,
 'lme_lead': 0.9675,
 'lme_nickel': 8.0683,
 'lme_zinc': 1.9298,
 'mcx_gold': 80488.6339,
 'mcx_gold_am': 79341.435,
 'mcx_gold_pm': 79432.6708,
 'mcx_silver': 1193.5198,
 'mcx_silver_am': 1183.2841,
 'mcx_silver_pm': 1184.185,
 'nickel': 8.0013,
 'palladium': 18651.7187,
 'platinum': 27740.1734,
 'silver': 987.3737,
 'zinc': 1.9269}
dict_items([('gold', 68878.0415), ('silver', 987.3737), ('platinum', 27740.1734), ('palladium', 18651.7187), ('lbma_gold_am', 69015.9927), ('lbma_gold_pm', 68841.9036), ('lbma_silver', 993.5452), ('lbma_platinum_am', 27756.8892), ('lbma_platinum_pm', 27869.9233), ('lbma_palladium_am', 18990.557), ('lbma_palladium_pm', 18989.7319), ('mcx_gold', 80488.6339), ('mcx_gold_am', 79341.435), ('mcx_gold_pm', 79432.6708), ('mcx_silver', 1193.5198), ('mcx_silver_am', 1183.2841), ('mcx_silver_pm', 1184.185), ('ibja_gold', 79694.0998), ('ibja_silver', 1182.4755), ('copper', 7.6879), ('aluminum', 1.5575), ('lead', 0.9734), ('nickel', 8.0013), ('zinc', 1.9269), ('lme_copper', 7.5229), ('lme_aluminum', 1.5705), ('lme_lead', 0.9675), ('lme_nickel', 8.0683), ('lme_zinc', 1.9298)])

In [9]:
for metal, price in data["metals"].items():
    print(metal.title(),  "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72
Lbma_Gold_Am Price: 69015.99
Lbma_Gold_Pm Price: 68841.9
Lbma_Silver Price: 993.55
Lbma_Platinum_Am Price: 27756.89
Lbma_Platinum_Pm Price: 27869.92
Lbma_Palladium_Am Price: 18990.56
Lbma_Palladium_Pm Price: 18989.73
Mcx_Gold Price: 80488.63
Mcx_Gold_Am Price: 79341.43
Mcx_Gold_Pm Price: 79432.67
Mcx_Silver Price: 1193.52
Mcx_Silver_Am Price: 1183.28
Mcx_Silver_Pm Price: 1184.18
Ibja_Gold Price: 79694.1
Ibja_Silver Price: 1182.48
Copper Price: 7.69
Aluminum Price: 1.56
Lead Price: 0.97
Nickel Price: 8.0
Zinc Price: 1.93
Lme_Copper Price: 7.52
Lme_Aluminum Price: 1.57
Lme_Lead Price: 0.97
Lme_Nickel Price: 8.07
Lme_Zinc Price: 1.93

In [10]:
for metal, price in data["metals"].items():
    if metal in ["gold", "silver", "platinum", "palladium"]:
        print(metal.title(), "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72

In [11]:
for metal, price in data["metals"].items():
    if metal in ["gold", "silver", "platinum", "palladium"]:
        print(metal.title(), "Price:", round(price, 2))
    else:
        print(metal.title(), "N/A")

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72
Lbma_Gold_Am N/A
Lbma_Gold_Pm N/A
Lbma_Silver N/A
Lbma_Platinum_Am N/A
Lbma_Platinum_Pm N/A
Lbma_Palladium_Am N/A
Lbma_Palladium_Pm N/A
Mcx_Gold N/A
Mcx_Gold_Am N/A
Mcx_Gold_Pm N/A
Mcx_Silver N/A
Mcx_Silver_Am N/A
Mcx_Silver_Pm N/A
Ibja_Gold N/A
Ibja_Silver N/A
Copper N/A
Aluminum N/A
Lead N/A
Nickel N/A
Zinc N/A
Lme_Copper N/A
Lme_Aluminum N/A
Lme_Lead N/A
Lme_Nickel N/A
Lme_Zinc N/A

In [12]:
for metal, price in data["metals"].items():
    if metal not in ["gold", "silver", "platinum", "palladium"]:
        continue

    print(metal.title(), "Price:", round(price, 2))

Gold Price: 68878.04
Silver Price: 987.37
Platinum Price: 27740.17
Palladium Price: 18651.72

In [13]:
for metal, price in data["metals"].items():
    if price <= 2000:
        print("Under 2000!", metal, round(price, 2))
    elif price < 50000:
        print("Between 2000 and 50000!",metal, round(price, 2))
    elif price >= 50000:
        print("Over 50000!",metal, round(price, 2))
    else: print("?????",metal, round(price, 2))

Over 50000! gold 68878.04
Under 2000! silver 987.37
Between 2000 and 50000! platinum 27740.17
Between 2000 and 50000! palladium 18651.72
Over 50000! lbma_gold_am 69015.99
Over 50000! lbma_gold_pm 68841.9
Under 2000! lbma_silver 993.55
Between 2000 and 50000! lbma_platinum_am 27756.89
Between 2000 and 50000! lbma_platinum_pm 27869.92
Between 2000 and 50000! lbma_palladium_am 18990.56
Between 2000 and 50000! lbma_palladium_pm 18989.73
Over 50000! mcx_gold 80488.63
Over 50000! mcx_gold_am 79341.43
Over 50000! mcx_gold_pm 79432.67
Under 2000! mcx_silver 1193.52
Under 2000! mcx_silver_am 1183.28
Under 2000! mcx_silver_pm 1184.18
Over 50000! ibja_gold 79694.1
Under 2000! ibja_silver 1182.48
Under 2000! copper 7.69
Under 2000! aluminum 1.56
Under 2000! lead 0.97
Under 2000! nickel 8.0
Under 2000! zinc 1.93
Under 2000! lme_copper 7.52
Under 2000! lme_aluminum 1.57
Under 2000! lme_lead 0.97
Under 2000! lme_nickel 8.07
Under 2000! lme_zinc 1.93

In [14]:
for metal, price in data["metals"].items():
    if price <= 2000:
        print("Under 2000!", metal, round(price, 2))

    else:
        if price >= 50000:
            print("Over 50000!", metal, round(price, 2))
        else:
            print("Between 2000 and 50000!", metal, round(price, 2))

Over 50000! gold 68878.04
Under 2000! silver 987.37
Between 2000 and 50000! platinum 27740.17
Between 2000 and 50000! palladium 18651.72
Over 50000! lbma_gold_am 69015.99
Over 50000! lbma_gold_pm 68841.9
Under 2000! lbma_silver 993.55
Between 2000 and 50000! lbma_platinum_am 27756.89
Between 2000 and 50000! lbma_platinum_pm 27869.92
Between 2000 and 50000! lbma_palladium_am 18990.56
Between 2000 and 50000! lbma_palladium_pm 18989.73
Over 50000! mcx_gold 80488.63
Over 50000! mcx_gold_am 79341.43
Over 50000! mcx_gold_pm 79432.67
Under 2000! mcx_silver 1193.52
Under 2000! mcx_silver_am 1183.28
Under 2000! mcx_silver_pm 1184.18
Over 50000! ibja_gold 79694.1
Under 2000! ibja_silver 1182.48
Under 2000! copper 7.69
Under 2000! aluminum 1.56
Under 2000! lead 0.97
Under 2000! nickel 8.0
Under 2000! zinc 1.93
Under 2000! lme_copper 7.52
Under 2000! lme_aluminum 1.57
Under 2000! lme_lead 0.97
Under 2000! lme_nickel 8.07
Under 2000! lme_zinc 1.93

In [15]:
for metal, price in data["metals"].items():
    if metal == "gold":
        if price > 50000:
            print("Gold is expensive!")
        else:
            print("Gold is below 50000")
    if metal == "silver":
        if price > 1200:
            print("Silver is expensive!")
        else:
            print("Silver is Cheap!")

Gold is expensive!
Silver is Cheap!

In [17]:

import pandas as pd

In [26]:
df = pd.DataFrame(data["metals"].items())
df.columns = ["Metal", "Price"]

print(df.head())
df

          Metal       Price
0          gold  68878.0415
1        silver    987.3737
2      platinum  27740.1734
3     palladium  18651.7187
4  lbma_gold_am  69015.9927

                Metal       Price
0                gold  68878.0415
1              silver    987.3737
2            platinum  27740.1734
3           palladium  18651.7187
4        lbma_gold_am  69015.9927
5        lbma_gold_pm  68841.9036
6         lbma_silver    993.5452
7    lbma_platinum_am  27756.8892
8    lbma_platinum_pm  27869.9233
9   lbma_palladium_am  18990.5570
10  lbma_palladium_pm  18989.7319
11           mcx_gold  80488.6339
12        mcx_gold_am  79341.4350
13        mcx_gold_pm  79432.6708
14         mcx_silver   1193.5198
15      mcx_silver_am   1183.2841
16      mcx_silver_pm   1184.1850
17          ibja_gold  79694.0998
18        ibja_silver   1182.4755
19             copper      7.6879
20           aluminum      1.5575
21               lead      0.9734
22             nickel      8.0013
23               zinc      1.9269
24         lme_copper      7.5229
25       lme_aluminum      1.5705
26           lme_lead      0.9675
27         lme_nickel      8.0683
28           lme_zinc      1.9298

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Metal   29 non-null     object
 1   Price   29 non-null     float64
dtypes: float64(1), object(1)
memory usage: 596.0+ bytes

In [30]:
df["Price"]

0     68878.0415
1       987.3737
2     27740.1734
3     18651.7187
4     69015.9927
5     68841.9036
6       993.5452
7     27756.8892
8     27869.9233
9     18990.5570
10    18989.7319
11    80488.6339
12    79341.4350
13    79432.6708
14     1193.5198
15     1183.2841
16     1184.1850
17    79694.0998
18     1182.4755
19        7.6879
20        1.5575
21        0.9734
22        8.0013
23        1.9269
24        7.5229
25        1.5705
26        0.9675
27        8.0683
28        1.9298
Name: Price, dtype: float64

In [31]:
df[["Metal", "Price"]]

                Metal       Price
0                gold  68878.0415
1              silver    987.3737
2            platinum  27740.1734
3           palladium  18651.7187
4        lbma_gold_am  69015.9927
5        lbma_gold_pm  68841.9036
6         lbma_silver    993.5452
7    lbma_platinum_am  27756.8892
8    lbma_platinum_pm  27869.9233
9   lbma_palladium_am  18990.5570
10  lbma_palladium_pm  18989.7319
11           mcx_gold  80488.6339
12        mcx_gold_am  79341.4350
13        mcx_gold_pm  79432.6708
14         mcx_silver   1193.5198
15      mcx_silver_am   1183.2841
16      mcx_silver_pm   1184.1850
17          ibja_gold  79694.0998
18        ibja_silver   1182.4755
19             copper      7.6879
20           aluminum      1.5575
21               lead      0.9734
22             nickel      8.0013
23               zinc      1.9269
24         lme_copper      7.5229
25       lme_aluminum      1.5705
26           lme_lead      0.9675
27         lme_nickel      8.0683
28           lme_zinc      1.9298

In [32]:
print(type(df["Price"]))
print(type(df[["Price"]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>